=== nemouu/wordsnake-hunt/res/schlangenjagd.dtd
<!ELEMENT Schlangenjagd (Zeit?, Dschungel, Schlangenarten, 
        Schlangen?)>
<!ELEMENT Zeit (Vorgabe, Abgabe?)> 
<!ATTLIST Zeit
    einheit (ms|s|min|h|d) "s"
>
<!ELEMENT Vorgabe (#PCDATA)>
<!ELEMENT Abgabe (#PCDATA)>
<!ELEMENT Dschungel (Feld*)>
<!ATTLIST Dschungel
    zeilen CDATA #REQUIRED
    spalten CDATA #REQUIRED
    zeichen CDATA #REQUIRED
>
<!ELEMENT Feld (#PCDATA)> 
<!ATTLIST Feld
    id ID #REQUIRED
    zeile CDATA #REQUIRED
    spalte CDATA #REQUIRED
    verwendbarkeit CDATA "1"
    punkte CDATA "1"
>
<!ELEMENT Schlangenarten (Schlangenart+)>
<!ELEMENT Schlangenart (Zeichenkette, Nachbarschaftsstruktur)>
<!ATTLIST Schlangenart
    id ID #REQUIRED
    punkte CDATA "1"
    anzahl CDATA #REQUIRED
>
<!ELEMENT Zeichenkette (#PCDATA)>
<!ELEMENT Nachbarschaftsstruktur (Parameter*)>
<!ATTLIST Nachbarschaftsstruktur
    typ CDATA #REQUIRED
>
<!ELEMENT Parameter EMPTY>
<!ATTLIST Parameter
    wert CDATA #REQUIRED
>
<!ELEMENT Schlangen (Schlange*)>
<!ELEMENT Schlange (Schlangenglied+)>
<!ATTLIST Schlange
    art IDREF #REQUIRED
>
<!ELEMENT Schlangenglied EMPTY>
<!ATTLIST Schlangenglied
    feld IDREF #REQUIRED
>

=== nemouu/wordsnake-hunt/res/sj_p9_unvollstaendig.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Schlangenjagd SYSTEM "schlangenjagd.dtd" >
<Schlangenjagd>
	<Zeit einheit="h">
		<Vorgabe>0.005</Vorgabe>
	</Zeit>
	<Dschungel zeilen="8" spalten="10" zeichen="ÁÀĂÂÄÓÒǑÔÖ">
	</Dschungel>
	<Schlangenarten>
		<Schlangenart id="A0" punkte="10" anzahl="3">
			<Zeichenkette>ANNA</Zeichenkette>
			<Nachbarschaftsstruktur typ="Distanz">
				<Parameter wert="1" />
			</Nachbarschaftsstruktur>
		</Schlangenart>
		<Schlangenart id="A1" punkte="1" anzahl="3">
			<Zeichenkette>ANNA</Zeichenkette>
			<Nachbarschaftsstruktur typ="Distanz">
				<Parameter wert="2" />
			</Nachbarschaftsstruktur>
		</Schlangenart>
		<Schlangenart id="A2" punkte="10" anzahl="3">
			<Zeichenkette>OTTO</Zeichenkette>
			<Nachbarschaftsstruktur typ="Distanz">
				<Parameter wert="1" />
			</Nachbarschaftsstruktur>
		</Schlangenart>
		<Schlangenart id="A3" punkte="1" anzahl="3">
			<Zeichenkette>OTTO</Zeichenkette>
			<Nachbarschaftsstruktur typ="Distanz">
				<Parameter wert="2" />
			</Nachbarschaftsstruktur>
		</Schlangenart>
		<Schlangenart id="A4" punkte="30" anzahl="1">
			<Zeichenkette>ANON</Zeichenkette>
			<Nachbarschaftsstruktur typ="Sprung">
				<Parameter wert="2" />
				<Parameter wert="1" />
			</Nachbarschaftsstruktur>
		</Schlangenart>
		<Schlangenart id="A5" punkte="20" anzahl="1">
			<Zeichenkette>NONA</Zeichenkette>
			<Nachbarschaftsstruktur typ="Sprung">
				<Parameter wert="2" />
				<Parameter wert="1" />
			</Nachbarschaftsstruktur>
		</Schlangenart>
	</Schlangenarten>
</Schlangenjagd>

=== nemouu/wordsnake-hunt/res/sj_nachmittag_unvollstaendig.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Schlangenjagd SYSTEM "schlangenjagd.dtd" >
<Schlangenjagd>
	<Zeit einheit="s">
		<Vorgabe>10.0</Vorgabe>
	</Zeit>
	<Dschungel zeilen="15" spalten="20" zeichen=".">
	</Dschungel>
	<Schlangenarten>
		<Schlangenart id="A0" punkte="1" anzahl="1">
			<Zeichenkette>FERNUNI</Zeichenkette>
			<Nachbarschaftsstruktur typ="Stern">
				<Parameter wert="2" />
				<Parameter wert="2" />
			</Nachbarschaftsstruktur>
		</Schlangenart>
		<Schlangenart id="A1" punkte="1" anzahl="1">
			<Zeichenkette>HAGEN</Zeichenkette>
			<Nachbarschaftsstruktur typ="Stern">
				<Parameter wert="3" />
				<Parameter wert="0" />
			</Nachbarschaftsstruktur>
		</Schlangenart>
		<Schlangenart id="A2" punkte="1" anzahl="1">
			<Zeichenkette>PROPRA</Zeichenkette>
			<Nachbarschaftsstruktur typ="Stern">
				<Parameter wert="0" />
				<Parameter wert="4" />
			</Nachbarschaftsstruktur>
		</Schlangenart>
	</Schlangenarten>
</Schlangenjagd>

=== nemouu/wordsnake-hunt/res/sj_p6_loesung.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Schlangenjagd SYSTEM "schlangenjagd.dtd">
<Schlangenjagd>
    <Zeit einheit="ms">
        <Vorgabe>2000.0</Vorgabe>
        <Abgabe>2000.00417</Abgabe>
    </Zeit>
    <Dschungel zeilen="6" spalten="6" zeichen="X">
        <Feld id="F0" zeile="0" spalte="0" verwendbarkeit="1" punkte="5">A</Feld>
        <Feld id="F1" zeile="0" spalte="1" verwendbarkeit="1" punkte="8">A</Feld>
        <Feld id="F2" zeile="0" spalte="2" verwendbarkeit="1" punkte="7">X</Feld>
        <Feld id="F3" zeile="0" spalte="3" verwendbarkeit="1" punkte="3">A</Feld>
        <Feld id="F4" zeile="0" spalte="4" verwendbarkeit="1" punkte="4">A</Feld>
        <Feld id="F5" zeile="0" spalte="5" verwendbarkeit="1" punkte="4">X</Feld>
        <Feld id="F6" zeile="1" spalte="0" verwendbarkeit="1" punkte="4">A</Feld>
        <Feld id="F7" zeile="1" spalte="1" verwendbarkeit="1" punkte="6">A</Feld>
        <Feld id="F8" zeile="1" spalte="2" verwendbarkeit="1" punkte="8">A</Feld>
        <Feld id="F9" zeile="1" spalte="3" verwendbarkeit="1" punkte="8">A</Feld>
        <Feld id="F10" zeile="1" spalte="4" verwendbarkeit="1" punkte="9">X</Feld>
        <Feld id="F11" zeile="1" spalte="5" verwendbarkeit="1" punkte="3">X</Feld>
        <Feld id="F12" zeile="2" spalte="0" verwendbarkeit="1" punkte="7">A</Feld>
        <Feld id="F13" zeile="2" spalte="1" verwendbarkeit="1" punkte="3">X</Feld>
        <Feld id="F14" zeile="2" spalte="2" verwendbarkeit="1" punkte="2">A</Feld>
        <Feld id="F15" zeile="2" spalte="3" verwendbarkeit="1" punkte="4">X</Feld>
        <Feld id="F16" zeile="2" spalte="4" verwendbarkeit="1" punkte="2">X</Feld>
        <Feld id="F17" zeile="2" spalte="5" verwendbarkeit="1" punkte="2">X</Feld>
        <Feld id="F18" zeile="3" spalte="0" verwendbarkeit="1" punkte="6">A</Feld>
        <Feld id="F19" zeile="3" spalte="1" verwendbarkeit="1" punkte="9">A</Feld>
        <Feld id="F20" zeile="3" spalte="2" verwendbarkeit="1" punkte="6">A</Feld>
        <Feld id="F21" zeile="3" spalte="3" verwendbarkeit="1" punkte="2">A</Feld>
        <Feld id="F22" zeile="3" spalte="4" verwendbarkeit="1" punkte="0">A</Feld>
        <Feld id="F23" zeile="3" spalte="5" verwendbarkeit="1" punkte="9">X</Feld>
        <Feld id="F24" zeile="4" spalte="0" verwendbarkeit="1" punkte="4">A</Feld>
        <Feld id="F25" zeile="4" spalte="1" verwendbarkeit="1" punkte="9">X</Feld>
        <Feld id="F26" zeile="4" spalte="2" verwendbarkeit="1" punkte="8">A</Feld>
        <Feld id="F27" zeile="4" spalte="3" verwendbarkeit="1" punkte="3">A</Feld>
        <Feld id="F28" zeile="4" spalte="4" verwendbarkeit="1" punkte="7">X</Feld>
        <Feld id="F29" zeile="4" spalte="5" verwendbarkeit="1" punkte="2">A</Feld>
        <Feld id="F30" zeile="5" spalte="0" verwendbarkeit="1" punkte="5">X</Feld>
        <Feld id="F31" zeile="5" spalte="1" verwendbarkeit="1" punkte="4">A</Feld>
        <Feld id="F32" zeile="5" spalte="2" verwendbarkeit="1" punkte="0">X</Feld>
        <Feld id="F33" zeile="5" spalte="3" verwendbarkeit="1" punkte="6">A</Feld>
        <Feld id="F34" zeile="5" spalte="4" verwendbarkeit="1" punkte="3">A</Feld>
        <Feld id="F35" zeile="5" spalte="5" verwendbarkeit="1" punkte="5">X</Feld>
    </Dschungel>
    <Schlangenarten>
        <Schlangenart id="A0" punkte="1" anzahl="2">
            <Zeichenkette>AA</Zeichenkette>
            <Nachbarschaftsstruktur typ="Distanz">
                <Parameter wert="1" />
            </Nachbarschaftsstruktur>
        </Schlangenart>
        <Schlangenart id="A1" punkte="5" anzahl="2">
            <Zeichenkette>AA</Zeichenkette>
            <Nachbarschaftsstruktur typ="Sprung">
                <Parameter wert="1" />
                <Parameter wert="0" />
            </Nachbarschaftsstruktur>
        </Schlangenart>
        <Schlangenart id="A2" punkte="5" anzahl="2">
            <Zeichenkette>AA</Zeichenkette>
            <Nachbarschaftsstruktur typ="Sprung">
                <Parameter wert="1" />
                <Parameter wert="1" />
            </Nachbarschaftsstruktur>
        </Schlangenart>
        <Schlangenart id="A3" punkte="10" anzahl="2">
            <Zeichenkette>AA</Zeichenkette>
            <Nachbarschaftsstruktur typ="Sprung">
                <Parameter wert="2" />
                <Parameter wert="1" />
            </Nachbarschaftsstruktur>
        </Schlangenart>
        <Schlangenart id="A4" punkte="100" anzahl="2">
            <Zeichenkette>AAA</Zeichenkette>
            <Nachbarschaftsstruktur typ="Sprung">
                <Parameter wert="3" />
                <Parameter wert="1" />
            </Nachbarschaftsstruktur>
        </Schlangenart>
    </Schlangenarten>
    <Schlangen>
        <Schlange art="A4">
            <Schlangenglied feld="F1" />
            <Schlangenglied feld="F18" />
            <Schlangenglied feld="F27" />
        </Schlange>
        <Schlange art="A4">
            <Schlangenglied feld="F9" />
            <Schlangenglied feld="F26" />
            <Schlangenglied feld="F7" />
        </Schlange>
        <Schlange art="A4">
            <Schlangenglied feld="F12" />
            <Schlangenglied feld="F31" />
            <Schlangenglied feld="F14" />
        </Schlange>
        <Schlange art="A4">
            <Schlangenglied feld="F20" />
            <Schlangenglied feld="F3" />
            <Schlangenglied feld="F22" />
        </Schlange>
        <Schlange art="A4">
            <Schlangenglied feld="F4" />
            <Schlangenglied feld="F21" />
            <Schlangenglied feld="F24" />
        </Schlange>
        <Schlange art="A3">
            <Schlangenglied feld="F19" />
            <Schlangenglied feld="F6" />
        </Schlange>
        <Schlange art="A3">
            <Schlangenglied feld="F33" />
            <Schlangenglied feld="F29" />
        </Schlange>
        <Schlange art="A3">
            <Schlangenglied feld="F0" />
            <Schlangenglied feld="F8" />
        </Schlange>
    </Schlangen>
</Schlangenjagd>

=== nemouu/wordsnake-hunt/res/Test2.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Schlangenjagd SYSTEM "schlangenjagd.dtd" >
<Schlangenjagd>
	<Zeit einheit="s">
		<Vorgabe>60.0</Vorgabe>
	</Zeit>
	<Dschungel zeilen="3" spalten="2" zeichen="ABCDEFGHIJKLMNOPQRSTUVWXYZ">
	</Dschungel>
	<Schlangenarten>
		<Schlangenart id="A0" punkte="1" anzahl="1">
			<Zeichenkette>DA</Zeichenkette>
			<Nachbarschaftsstruktur typ="Distanz">
				<Parameter wert="1" />
			</Nachbarschaftsstruktur>
		</Schlangenart>
		<Schlangenart id="A1" punkte="1" anzahl="1">
			<Zeichenkette>IM</Zeichenkette>
			<Nachbarschaftsstruktur typ="Sprung">
				<Parameter wert="1" />
				<Parameter wert="2" />
			</Nachbarschaftsstruktur>
		</Schlangenart>
		<Schlangenart id="A2" punkte="1" anzahl="1">
			<Zeichenkette>SO</Zeichenkette>
			<Nachbarschaftsstruktur typ="Sprung">
				<Parameter wert="1" />
				<Parameter wert="2" />
			</Nachbarschaftsstruktur>
		</Schlangenart>
	</Schlangenarten>
</Schlangenjagd>

=== nemouu/wordsnake-hunt/res/sj_p5_unvollstaendig.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Schlangenjagd SYSTEM "schlangenjagd.dtd" >
<Schlangenjagd>
	<Zeit einheit="s">
		<Vorgabe>10.0</Vorgabe>
	</Zeit>
	<Dschungel zeilen="20" spalten="20" zeichen="ABCDEFGHIJKLMNOPQRSTUVWXYZ">
	</Dschungel>
	<Schlangenarten>
		<Schlangenart id="A0" punkte="1" anzahl="3">
			<Zeichenkette>FERNUNI</Zeichenkette>
			<Nachbarschaftsstruktur typ="Distanz">
				<Parameter wert="1" />
			</Nachbarschaftsstruktur>
		</Schlangenart>
		<Schlangenart id="A1" punkte="1" anzahl="3">
			<Zeichenkette>HAGEN</Zeichenkette>
			<Nachbarschaftsstruktur typ="Sprung">
				<Parameter wert="2" />
				<Parameter wert="1" />
			</Nachbarschaftsstruktur>
		</Schlangenart>
		<Schlangenart id="A2" punkte="1" anzahl="3">
			<Zeichenkette>ANACONDA</Zeichenkette>
			<Nachbarschaftsstruktur typ="Sprung">
				<Parameter wert="3" />
				<Parameter wert="2" />
			</Nachbarschaftsstruktur>
		</Schlangenart>
	</Schlangenarten>
</Schlangenjagd>

=== nemouu/wordsnake-hunt/res/sj_p13_unvollstaendig.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Schlangenjagd SYSTEM "schlangenjagd.dtd" >
<Schlangenjagd>
	<Zeit einheit="s">
		<Vorgabe>10.0</Vorgabe>
	</Zeit>
	<Dschungel zeilen="20" spalten="20" zeichen="'">
	</Dschungel>
    <Schlangenarten>
        <Schlangenart id="A0" punkte="150" anzahl="1">
            <Zeichenkette>01000110010001010101001001001110010101010100111001001001</Zeichenkette>
            <Nachbarschaftsstruktur typ="Distanz">
                <Parameter wert="1" />
            </Nachbarschaftsstruktur>
        </Schlangenart>
        <Schlangenart id="A1" punkte="100" anzahl="1">
            <Zeichenkette>0100100001000001010001110100010101001110</Zeichenkette>
            <Nachbarschaftsstruktur typ="Distanz">
                <Parameter wert="1" />
            </Nachbarschaftsstruktur>
        </Schlangenart>
    </Schlangenarten>
</Schlangenjagd>

=== nemouu/wordsnake-hunt/res/sj_p4_unvollstaendig.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Schlangenjagd SYSTEM "schlangenjagd.dtd" >
<Schlangenjagd>
	<Zeit einheit="s">
		<Vorgabe>10.0</Vorgabe>
	</Zeit>
	<Dschungel zeilen="5" spalten="8" zeichen="ABCDEFGHIJKLMNOPQRSTUVWXYZ">
	</Dschungel>
	<Schlangenarten>
		<Schlangenart id="A0" punkte="1" anzahl="1">
			<Zeichenkette>ÄSKULAPNATTER</Zeichenkette>
			<Nachbarschaftsstruktur typ="Distanz">
				<Parameter wert="2" />
			</Nachbarschaftsstruktur>
		</Schlangenart>
		<Schlangenart id="A1" punkte="1" anzahl="1">
			<Zeichenkette>RINGELNATTER</Zeichenkette>
			<Nachbarschaftsstruktur typ="Distanz">
				<Parameter wert="2" />
			</Nachbarschaftsstruktur>
		</Schlangenart>
		<Schlangenart id="A2" punkte="1" anzahl="1">
			<Zeichenkette>SCHLINGNATTER</Zeichenkette>
			<Nachbarschaftsstruktur typ="Distanz">
				<Parameter wert="2" />
			</Nachbarschaftsstruktur>
		</Schlangenart>
	</Schlangenarten>
</Schlangenjagd>

=== nemouu/wordsnake-hunt/res/sj_p11_probleminstanz.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Schlangenjagd SYSTEM "schlangenjagd.dtd">
<Schlangenjagd>
    <Zeit einheit="s">
        <Vorgabe>10.0</Vorgabe>
    </Zeit>
    <Dschungel zeilen="7" spalten="7" zeichen="AEIOU">
        <Feld id="F0" zeile="0" spalte="0" verwendbarkeit="1" punkte="5">I</Feld>
        <Feld id="F1" zeile="0" spalte="1" verwendbarkeit="1" punkte="8">M</Feld>
        <Feld id="F2" zeile="0" spalte="2" verwendbarkeit="1" punkte="7">U</Feld>
        <Feld id="F3" zeile="0" spalte="3" verwendbarkeit="1" punkte="3">B</Feld>
        <Feld id="F4" zeile="0" spalte="4" verwendbarkeit="2" punkte="4">L</Feld>
        <Feld id="F5" zeile="0" spalte="5" verwendbarkeit="1" punkte="4">I</Feld>
        <Feld id="F6" zeile="0" spalte="6" verwendbarkeit="1" punkte="4">A</Feld>
        <Feld id="F7" zeile="1" spalte="0" verwendbarkeit="1" punkte="6">A</Feld>
        <Feld id="F8" zeile="1" spalte="1" verwendbarkeit="1" punkte="8">V</Feld>
        <Feld id="F9" zeile="1" spalte="2" verwendbarkeit="1" punkte="8">T</Feld>
        <Feld id="F10" zeile="1" spalte="3" verwendbarkeit="2" punkte="9">E</Feld>
        <Feld id="F11" zeile="1" spalte="4" verwendbarkeit="2" punkte="3">I</Feld>
        <Feld id="F12" zeile="1" spalte="5" verwendbarkeit="1" punkte="7">P</Feld>
        <Feld id="F13" zeile="1" spalte="6" verwendbarkeit="1" punkte="3">I</Feld>
        <Feld id="F14" zeile="2" spalte="0" verwendbarkeit="1" punkte="2">I</Feld>
        <Feld id="F15" zeile="2" spalte="1" verwendbarkeit="1" punkte="4">A</Feld>
        <Feld id="F16" zeile="2" spalte="2" verwendbarkeit="1" punkte="2">V</Feld>
        <Feld id="F17" zeile="2" spalte="3" verwendbarkeit="1" punkte="2">E</Feld>
        <Feld id="F18" zeile="2" spalte="4" verwendbarkeit="3" punkte="6">A</Feld>
        <Feld id="F19" zeile="2" spalte="5" verwendbarkeit="2" punkte="9">N</Feld>
        <Feld id="F20" zeile="2" spalte="6" verwendbarkeit="2" punkte="6">N</Feld>
        <Feld id="F21" zeile="3" spalte="0" verwendbarkeit="1" punkte="2">L</Feld>
        <Feld id="F22" zeile="3" spalte="1" verwendbarkeit="1" punkte="0">E</Feld>
        <Feld id="F23" zeile="3" spalte="2" verwendbarkeit="1" punkte="9">U</Feld>
        <Feld id="F24" zeile="3" spalte="3" verwendbarkeit="1" punkte="4">I</Feld>
        <Feld id="F25" zeile="3" spalte="4" verwendbarkeit="1" punkte="9">R</Feld>
        <Feld id="F26" zeile="3" spalte="5" verwendbarkeit="2" punkte="8">A</Feld>
        <Feld id="F27" zeile="3" spalte="6" verwendbarkeit="2" punkte="3">A</Feld>
        <Feld id="F28" zeile="4" spalte="0" verwendbarkeit="1" punkte="7">Y</Feld>
        <Feld id="F29" zeile="4" spalte="1" verwendbarkeit="1" punkte="2">S</Feld>
        <Feld id="F30" zeile="4" spalte="2" verwendbarkeit="2" punkte="5">A</Feld>
        <Feld id="F31" zeile="4" spalte="3" verwendbarkeit="1" punkte="4">A</Feld>
        <Feld id="F32" zeile="4" spalte="4" verwendbarkeit="3" punkte="0">E</Feld>
        <Feld id="F33" zeile="4" spalte="5" verwendbarkeit="1" punkte="6">A</Feld>
        <Feld id="F34" zeile="4" spalte="6" verwendbarkeit="1" punkte="3">D</Feld>
        <Feld id="F35" zeile="5" spalte="0" verwendbarkeit="1" punkte="5">M</Feld>
        <Feld id="F36" zeile="5" spalte="1" verwendbarkeit="1" punkte="9">D</Feld>
        <Feld id="F37" zeile="5" spalte="2" verwendbarkeit="1" punkte="0">V</Feld>
        <Feld id="F38" zeile="5" spalte="3" verwendbarkeit="1" punkte="5">L</Feld>
        <Feld id="F39" zeile="5" spalte="4" verwendbarkeit="1" punkte="4">O</Feld>
        <Feld id="F40" zeile="5" spalte="5" verwendbarkeit="1" punkte="5">L</Feld>
        <Feld id="F41" zeile="5" spalte="6" verwendbarkeit="1" punkte="0">S</Feld>
        <Feld id="F42" zeile="6" spalte="0" verwendbarkeit="1" punkte="7">I</Feld>
        <Feld id="F43" zeile="6" spalte="1" verwendbarkeit="2" punkte="7">A</Feld>
        <Feld id="F44" zeile="6" spalte="2" verwendbarkeit="1" punkte="7">A</Feld>
        <Feld id="F45" zeile="6" spalte="3" verwendbarkeit="1" punkte="2">A</Feld>
        <Feld id="F46" zeile="6" spalte="4" verwendbarkeit="1" punkte="0">Z</Feld>
        <Feld id="F47" zeile="6" spalte="5" verwendbarkeit="1" punkte="8">I</Feld>
        <Feld id="F48" zeile="6" spalte="6" verwendbarkeit="1" punkte="0">O</Feld>
    </Dschungel>
    <Schlangenarten>
        <Schlangenart id="A0" punkte="10" anzahl="1">
            <Zeichenkette>ADA</Zeichenkette>
            <Nachbarschaftsstruktur typ="Distanz">
                <Parameter wert="1" />
            </Nachbarschaftsstruktur>
        </Schlangenart>
        <Schlangenart id="A1" punkte="10" anzahl="1">
            <Zeichenkette>AMY</Zeichenkette>
            <Nachbarschaftsstruktur typ="Distanz">
                <Parameter wert="1" />
            </Nachbarschaftsstruktur>
        </Schlangenart>
        <Schlangenart id="A2" punkte="10" anzahl="1">
            <Zeichenkette>ANN</Zeichenkette>
            <Nachbarschaftsstruktur typ="Distanz">
                <Parameter wert="1" />
            </Nachbarschaftsstruktur>
        </Schlangenart>
        <Schlangenart id="A3" punkte="10" anzahl="1">
            <Zeichenkette>AVA</Zeichenkette>
            <Nachbarschaftsstruktur typ="Distanz">
                <Parameter wert="1" />
            </Nachbarschaftsstruktur>
        </Schlangenart>
        <Schlangenart id="A4" punkte="10" anzahl="1">
            <Zeichenkette>BEA</Zeichenkette>
            <Nachbarschaftsstruktur typ="Distanz">
                <Parameter wert="1" />
            </Nachbarschaftsstruktur>
        </Schlangenart>
        <Schlangenart id="A5" punkte="10" anzahl="1">
            <Zeichenkette>ELA</Zeichenkette>
            <Nachbarschaftsstruktur typ="Distanz">
                <Parameter wert="1" />
            </Nachbarschaftsstruktur>
        </Schlangenart>
        <Schlangenart id="A6" punkte="10" anzahl="1">
            <Zeichenkette>EVA</Zeichenkette>
            <Nachbarschaftsstruktur typ="Distanz">
                <Parameter wert="1" />
            </Nachbarschaftsstruktur>
        </Schlangenart>
        <Schlangenart id="A7" punkte="10" anzahl="1">
            <Zeichenkette>IDA</Zeichenkette>
            <Nachbarschaftsstruktur typ="Distanz">
                <Parameter wert="1" />
            </Nachbarschaftsstruktur>
        </Schlangenart>
        <Schlangenart id="A8" punkte="10" anzahl="1">
            <Zeichenkette>INA</Zeichenkette>
            <Nachbarschaftsstruktur typ="Distanz">
                <Parameter wert="1" />
            </Nachbarschaftsstruktur>
        </Schlangenart>
        <Schlangenart id="A9" punkte="10" anzahl="1">
            <Zeichenkette>ISA</Zeichenkette>
            <Nachbarschaftsstruktur typ="Distanz">
                <Parameter wert="1" />
            </Nachbarschaftsstruktur>
        </Schlangenart>
        <Schlangenart id="A10" punkte="10" anzahl="1">
            <Zeichenkette>LEA</Zeichenkette>
            <Nachbarschaftsstruktur typ="Distanz">
                <Parameter wert="1" />
            </Nachbarschaftsstruktur>
        </Schlangenart>
        <Schlangenart id="A11" punkte="10" anzahl="1">
            <Zeichenkette>LIA</Zeichenkette>
            <Nachbarschaftsstruktur typ="Distanz">
                <Parameter wert="1" />
            </Nachbarschaftsstruktur>
        </Schlangenart>
        <Schlangenart id="A12" punkte="10" anzahl="1">
            <Zeichenkette>LIN</Zeichenkette>
            <Nachbarschaftsstruktur typ="Distanz">
                <Parameter wert="1" />
            </Nachbarschaftsstruktur>
        </Schlangenart>
        <Schlangenart id="A13" punkte="10" anzahl="1">
            <Zeichenkette>LIV</Zeichenkette>
            <Nachbarschaftsstruktur typ="Distanz">
                <Parameter wert="1" />
            </Nachbarschaftsstruktur>
        </Schlangenart>
        <Schlangenart id="A14" punkte="10" anzahl="1">
            <Zeichenkette>MIA</Zeichenkette>
            <Nachbarschaftsstruktur typ="Distanz">
                <Parameter wert="1" />
            </Nachbarschaftsstruktur>
        </Schlangenart>
        <Schlangenart id="A15" punkte="10" anzahl="1">
            <Zeichenkette>PIA</Zeichenkette>
            <Nachbarschaftsstruktur typ="Distanz">
                <Parameter wert="1" />
            </Nachbarschaftsstruktur>
        </Schlangenart>
        <Schlangenart id="A16" punkte="10" anzahl="1">
            <Zeichenkette>RIA</Zeichenkette>
            <Nachbarschaftsstruktur typ="Distanz">
                <Parameter wert="1" />
            </Nachbarschaftsstruktur>
        </Schlangenart>
        <Schlangenart id="A17" punkte="10" anzahl="1">
            <Zeichenkette>SUE</Zeichenkette>
            <Nachbarschaftsstruktur typ="Distanz">
                <Parameter wert="1" />
            </Nachbarschaftsstruktur>
        </Schlangenart>
        <Schlangenart id="A18" punkte="10" anzahl="1">
            <Zeichenkette>UTE</Zeichenkette>
            <Nachbarschaftsstruktur typ="Distanz">
                <Parameter wert="1" />
            </Nachbarschaftsstruktur>
        </Schlangenart>
        <Schlangenart id="A19" punkte="10" anzahl="1">
            <Zeichenkette>ZOE</Zeichenkette>
            <Nachbarschaftsstruktur typ="Distanz">
                <Parameter wert="1" />
            </Nachbarschaftsstruktur>
        </Schlangenart>
    </Schlangenarten>
    <Schlangen />
</Schlangenjagd>
