=== nemouu/wordsnake-hunt/res/schlangenjagd.dtd
<!ELEMENT Schlangenjagd (Zeit?, Dschungel, Schlangenarten, 
        Schlangen?)>
<!ELEMENT Zeit (Vorgabe, Abgabe?)> 
<!ATTLIST Zeit
    einheit (ms|s|min|h|d) "s"
>
<!ELEMENT Vorgabe (#PCDATA)>
<!ELEMENT Abgabe (#PCDATA)>
<!ELEMENT Dschungel (Feld*)>
<!ATTLIST Dschungel
    zeilen CDATA #REQUIRED
    spalten CDATA #REQUIRED
    zeichen CDATA #REQUIRED
>
<!ELEMENT Feld (#PCDATA)> 
<!ATTLIST Feld
    id ID #REQUIRED
    zeile CDATA #REQUIRED
    spalte CDATA #REQUIRED
    verwendbarkeit CDATA "1"
    punkte CDATA "1"
>
<!ELEMENT Schlangenarten (Schlangenart+)>
<!ELEMENT Schlangenart (Zeichenkette, Nachbarschaftsstruktur)>
<!ATTLIST Schlangenart
    id ID #REQUIRED
    punkte CDATA "1"
    anzahl CDATA #REQUIRED
>
<!ELEMENT Zeichenkette (#PCDATA)>
<!ELEMENT Nachbarschaftsstruktur (Parameter*)>
<!ATTLIST Nachbarschaftsstruktur
    typ CDATA #REQUIRED
>
<!ELEMENT Parameter EMPTY>
<!ATTLIST Parameter
    wert CDATA #REQUIRED
>
<!ELEMENT Schlangen (Schlange*)>
<!ELEMENT Schlange (Schlangenglied+)>
<!ATTLIST Schlange
    art IDREF #REQUIRED
>
<!ELEMENT Schlangenglied EMPTY>
<!ATTLIST Schlangenglied
    feld IDREF #REQUIRED
>

=== nemouu/wordsnake-hunt/res/sj_p4_probleminstanz_test.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Schlangenjagd SYSTEM "schlangenjagd.dtd">
<Schlangenjagd>
  <Zeit einheit="s">
    <Vorgabe>10.0</Vorgabe>
    <Abgabe>3.968441198</Abgabe>
  </Zeit>
  <Dschungel zeilen="5" spalten="8" zeichen="ABCDEFGHIJKLMNOPQRSTUVWXYZ">
    <Feld id="F0" zeile="0" spalte="0" verwendbarkeit="1" punkte="1">N</Feld>
    <Feld id="F1" zeile="0" spalte="1" verwendbarkeit="1" punkte="1">G</Feld>
    <Feld id="F2" zeile="0" spalte="2" verwendbarkeit="1" punkte="1">R</Feld>
    <Feld id="F3" zeile="0" spalte="3" verwendbarkeit="1" punkte="1">N</Feld>
    <Feld id="F4" zeile="0" spalte="4" verwendbarkeit="1" punkte="1">T</Feld>
    <Feld id="F5" zeile="0" spalte="5" verwendbarkeit="1" punkte="1">A</Feld>
    <Feld id="F6" zeile="0" spalte="6" verwendbarkeit="1" punkte="1">R</Feld>
    <Feld id="F7" zeile="0" spalte="7" verwendbarkeit="1" punkte="1">E</Feld>
    <Feld id="F8" zeile="1" spalte="0" verwendbarkeit="1" punkte="1">H</Feld>
    <Feld id="F9" zeile="1" spalte="1" verwendbarkeit="1" punkte="1">I</Feld>
    <Feld id="F10" zeile="1" spalte="2" verwendbarkeit="1" punkte="1">E</Feld>
    <Feld id="F11" zeile="1" spalte="3" verwendbarkeit="1" punkte="1">I</Feld>
    <Feld id="F12" zeile="1" spalte="4" verwendbarkeit="1" punkte="1">T</Feld>
    <Feld id="F13" zeile="1" spalte="5" verwendbarkeit="1" punkte="1">A</Feld>
    <Feld id="F14" zeile="1" spalte="6" verwendbarkeit="1" punkte="1">T</Feld>
    <Feld id="F15" zeile="1" spalte="7" verwendbarkeit="1" punkte="1">Ä</Feld>
    <Feld id="F16" zeile="2" spalte="0" verwendbarkeit="1" punkte="1">C</Feld>
    <Feld id="F17" zeile="2" spalte="1" verwendbarkeit="1" punkte="1">R</Feld>
    <Feld id="F18" zeile="2" spalte="2" verwendbarkeit="1" punkte="1">N</Feld>
    <Feld id="F19" zeile="2" spalte="3" verwendbarkeit="1" punkte="1">N</Feld>
    <Feld id="F20" zeile="2" spalte="4" verwendbarkeit="1" punkte="1">E</Feld>
    <Feld id="F21" zeile="2" spalte="5" verwendbarkeit="1" punkte="1">N</Feld>
    <Feld id="F22" zeile="2" spalte="6" verwendbarkeit="1" punkte="1">S</Feld>
    <Feld id="F23" zeile="2" spalte="7" verwendbarkeit="1" punkte="1">T</Feld>
    <Feld id="F24" zeile="3" spalte="0" verwendbarkeit="1" punkte="1">G</Feld>
    <Feld id="F25" zeile="3" spalte="1" verwendbarkeit="1" punkte="1">R</Feld>
    <Feld id="F26" zeile="3" spalte="2" verwendbarkeit="1" punkte="1">L</Feld>
    <Feld id="F27" zeile="3" spalte="3" verwendbarkeit="1" punkte="1">P</Feld>
    <Feld id="F28" zeile="3" spalte="4" verwendbarkeit="1" punkte="1">T</Feld>
    <Feld id="F29" zeile="3" spalte="5" verwendbarkeit="1" punkte="1">L</Feld>
    <Feld id="F30" zeile="3" spalte="6" verwendbarkeit="1" punkte="1">K</Feld>
    <Feld id="F31" zeile="3" spalte="7" verwendbarkeit="1" punkte="1">U</Feld>
    <Feld id="F32" zeile="4" spalte="0" verwendbarkeit="1" punkte="1">E</Feld>
    <Feld id="F33" zeile="4" spalte="1" verwendbarkeit="1" punkte="1">L</Feld>
    <Feld id="F34" zeile="4" spalte="2" verwendbarkeit="1" punkte="1">S</Feld>
    <Feld id="F35" zeile="4" spalte="3" verwendbarkeit="1" punkte="1">A</Feld>
    <Feld id="F36" zeile="4" spalte="4" verwendbarkeit="1" punkte="1">R</Feld>
    <Feld id="F37" zeile="4" spalte="5" verwendbarkeit="1" punkte="1">A</Feld>
    <Feld id="F38" zeile="4" spalte="6" verwendbarkeit="1" punkte="1">T</Feld>
    <Feld id="F39" zeile="4" spalte="7" verwendbarkeit="1" punkte="1">A</Feld>
  </Dschungel>
  <Schlangenarten>
    <Schlangenart id="A0" punkte="1" anzahl="1">
      <Zeichenkette>ÄSKULAPNATTER</Zeichenkette>
      <Nachbarschaftsstruktur typ="Distanz">
        <Parameter wert="2" />
      </Nachbarschaftsstruktur>
    </Schlangenart>
    <Schlangenart id="A1" punkte="1" anzahl="1">
      <Zeichenkette>RINGELNATTER</Zeichenkette>
      <Nachbarschaftsstruktur typ="Distanz">
        <Parameter wert="2" />
      </Nachbarschaftsstruktur>
    </Schlangenart>
    <Schlangenart id="A2" punkte="1" anzahl="1">
      <Zeichenkette>SCHLINGNATTER</Zeichenkette>
      <Nachbarschaftsstruktur typ="Distanz">
        <Parameter wert="2" />
      </Nachbarschaftsstruktur>
    </Schlangenart>
  </Schlangenarten>
  <Schlangen>
    <Schlange art="A0">
      <Schlangenglied feld="F15" />
      <Schlangenglied feld="F22" />
      <Schlangenglied feld="F30" />
      <Schlangenglied feld="F31" />
      <Schlangenglied feld="F29" />
      <Schlangenglied feld="F37" />
      <Schlangenglied feld="F27" />
      <Schlangenglied feld="F21" />
      <Schlangenglied feld="F13" />
      <Schlangenglied feld="F12" />
      <Schlangenglied feld="F4" />
      <Schlangenglied feld="F10" />
      <Schlangenglied feld="F17" />
    </Schlange>
    <Schlange art="A2">
      <Schlangenglied feld="F34" />
      <Schlangenglied feld="F16" />
      <Schlangenglied feld="F8" />
      <Schlangenglied feld="F26" />
      <Schlangenglied feld="F9" />
      <Schlangenglied feld="F0" />
      <Schlangenglied feld="F1" />
      <Schlangenglied feld="F3" />
      <Schlangenglied feld="F5" />
      <Schlangenglied feld="F14" />
      <Schlangenglied feld="F23" />
      <Schlangenglied feld="F7" />
      <Schlangenglied feld="F6" />
    </Schlange>
    <Schlange art="A1">
      <Schlangenglied feld="F2" />
      <Schlangenglied feld="F11" />
      <Schlangenglied feld="F18" />
      <Schlangenglied feld="F24" />
      <Schlangenglied feld="F32" />
      <Schlangenglied feld="F33" />
      <Schlangenglied feld="F19" />
      <Schlangenglied feld="F35" />
      <Schlangenglied feld="F28" />
      <Schlangenglied feld="F38" />
      <Schlangenglied feld="F20" />
      <Schlangenglied feld="F36" />
    </Schlange>
  </Schlangen>
</Schlangenjagd>

=== nemouu/wordsnake-hunt/res/sj_p2_unvollstaendig.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Schlangenjagd SYSTEM "schlangenjagd.dtd" >
<Schlangenjagd>
	<Zeit einheit="s">
		<Vorgabe>10.0</Vorgabe>
	</Zeit>
	<Dschungel zeilen="5" spalten="10" zeichen="ABCDEFGHIJKLMNOPQRSTUVWXYZ">
	</Dschungel>
	<Schlangenarten>
		<Schlangenart id="A0" punkte="1" anzahl="1">
			<Zeichenkette>DIE</Zeichenkette>
			<Nachbarschaftsstruktur typ="Distanz">
				<Parameter wert="1" />
			</Nachbarschaftsstruktur>
		</Schlangenart>
		<Schlangenart id="A1" punkte="1" anzahl="1">
			<Zeichenkette>DIES</Zeichenkette>
			<Nachbarschaftsstruktur typ="Distanz">
				<Parameter wert="1" />
			</Nachbarschaftsstruktur>
		</Schlangenart>
		<Schlangenart id="A2" punkte="1" anzahl="1">
			<Zeichenkette>DIESE</Zeichenkette>
			<Nachbarschaftsstruktur typ="Distanz">
				<Parameter wert="1" />
			</Nachbarschaftsstruktur>
		</Schlangenart>
		<Schlangenart id="A3" punkte="1" anzahl="1">
			<Zeichenkette>DIESES</Zeichenkette>
			<Nachbarschaftsstruktur typ="Distanz">
				<Parameter wert="1" />
			</Nachbarschaftsstruktur>
		</Schlangenart>
		<Schlangenart id="A4" punkte="1" anzahl="1">
			<Zeichenkette>DIESEN</Zeichenkette>
			<Nachbarschaftsstruktur typ="Distanz">
				<Parameter wert="1" />
			</Nachbarschaftsstruktur>
		</Schlangenart>
		<Schlangenart id="A5" punkte="1" anzahl="1">
			<Zeichenkette>DIESER</Zeichenkette>
			<Nachbarschaftsstruktur typ="Distanz">
				<Parameter wert="1" />
			</Nachbarschaftsstruktur>
		</Schlangenart>
	</Schlangenarten>
</Schlangenjagd>

=== nemouu/wordsnake-hunt/res/sj_p10_unvollstaendig.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Schlangenjagd SYSTEM "schlangenjagd.dtd" >
<Schlangenjagd>
	<Zeit einheit="d">
		<Vorgabe>0.0002</Vorgabe>
	</Zeit>
	<Dschungel zeilen="6" spalten="6" zeichen="BELN">
	</Dschungel>
	<Schlangenarten>
		<Schlangenart id="A0" punkte="20" anzahl="2">
			<Zeichenkette>LEBEN</Zeichenkette>
			<Nachbarschaftsstruktur typ="Distanz">
				<Parameter wert="2" />
			</Nachbarschaftsstruktur>
		</Schlangenart>
		<Schlangenart id="A1" punkte="1" anzahl="2">
			<Zeichenkette>NEBEL</Zeichenkette>
			<Nachbarschaftsstruktur typ="Distanz">
				<Parameter wert="3" />
			</Nachbarschaftsstruktur>
		</Schlangenart>
	</Schlangenarten>
</Schlangenjagd>

=== nemouu/wordsnake-hunt/res/sj_p8_probleminstanz.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Schlangenjagd SYSTEM "schlangenjagd.dtd">
<Schlangenjagd>
    <Zeit einheit="min">
        <Vorgabe>0.2</Vorgabe>
    </Zeit>
    <Dschungel zeilen="8" spalten="8" zeichen="☀☁☂☃☄★☆☇☔☕☼☽☾♨♫⚘⚽⛄⛅⛆⛈⛐⛰⛵⛷⛸⛹⛺">
        <Feld id="F0" zeile="0" spalte="0" verwendbarkeit="1" punkte="5">☻</Feld>
        <Feld id="F1" zeile="0" spalte="1" verwendbarkeit="1" punkte="8">☺</Feld>
        <Feld id="F2" zeile="0" spalte="2" verwendbarkeit="1" punkte="7">☻</Feld>
        <Feld id="F3" zeile="0" spalte="3" verwendbarkeit="1" punkte="3">⛸</Feld>
        <Feld id="F4" zeile="0" spalte="4" verwendbarkeit="1" punkte="4">☄</Feld>
        <Feld id="F5" zeile="0" spalte="5" verwendbarkeit="1" punkte="4">☺</Feld>
        <Feld id="F6" zeile="0" spalte="6" verwendbarkeit="1" punkte="4">☻</Feld>
        <Feld id="F7" zeile="0" spalte="7" verwendbarkeit="1" punkte="6">☺</Feld>
        <Feld id="F8" zeile="1" spalte="0" verwendbarkeit="1" punkte="8">☺</Feld>
        <Feld id="F9" zeile="1" spalte="1" verwendbarkeit="1" punkte="8">☻</Feld>
        <Feld id="F10" zeile="1" spalte="2" verwendbarkeit="1" punkte="9">☺</Feld>
        <Feld id="F11" zeile="1" spalte="3" verwendbarkeit="1" punkte="3">☺</Feld>
        <Feld id="F12" zeile="1" spalte="4" verwendbarkeit="1" punkte="7">☻</Feld>
        <Feld id="F13" zeile="1" spalte="5" verwendbarkeit="1" punkte="3">☻</Feld>
        <Feld id="F14" zeile="1" spalte="6" verwendbarkeit="1" punkte="2">⚘</Feld>
        <Feld id="F15" zeile="1" spalte="7" verwendbarkeit="1" punkte="4">☻</Feld>
        <Feld id="F16" zeile="2" spalte="0" verwendbarkeit="1" punkte="2">P</Feld>
        <Feld id="F17" zeile="2" spalte="1" verwendbarkeit="1" punkte="2">☺</Feld>
        <Feld id="F18" zeile="2" spalte="2" verwendbarkeit="1" punkte="6">P</Feld>
        <Feld id="F19" zeile="2" spalte="3" verwendbarkeit="1" punkte="9">R</Feld>
        <Feld id="F20" zeile="2" spalte="4" verwendbarkeit="1" punkte="6">☻</Feld>
        <Feld id="F21" zeile="2" spalte="5" verwendbarkeit="1" punkte="2">⛐</Feld>
        <Feld id="F22" zeile="2" spalte="6" verwendbarkeit="1" punkte="0">☺</Feld>
        <Feld id="F23" zeile="2" spalte="7" verwendbarkeit="1" punkte="9">☺</Feld>
        <Feld id="F24" zeile="3" spalte="0" verwendbarkeit="1" punkte="4">☻</Feld>
        <Feld id="F25" zeile="3" spalte="1" verwendbarkeit="1" punkte="9">R</Feld>
        <Feld id="F26" zeile="3" spalte="2" verwendbarkeit="1" punkte="8">☺</Feld>
        <Feld id="F27" zeile="3" spalte="3" verwendbarkeit="1" punkte="3">♡</Feld>
        <Feld id="F28" zeile="3" spalte="4" verwendbarkeit="1" punkte="7">☺</Feld>
        <Feld id="F29" zeile="3" spalte="5" verwendbarkeit="1" punkte="2">☺</Feld>
        <Feld id="F30" zeile="3" spalte="6" verwendbarkeit="1" punkte="5">☺</Feld>
        <Feld id="F31" zeile="3" spalte="7" verwendbarkeit="1" punkte="4">☻</Feld>
        <Feld id="F32" zeile="4" spalte="0" verwendbarkeit="1" punkte="0">☻</Feld>
        <Feld id="F33" zeile="4" spalte="1" verwendbarkeit="1" punkte="6">☻</Feld>
        <Feld id="F34" zeile="4" spalte="2" verwendbarkeit="1" punkte="3">☺</Feld>
        <Feld id="F35" zeile="4" spalte="3" verwendbarkeit="1" punkte="5">☻</Feld>
        <Feld id="F36" zeile="4" spalte="4" verwendbarkeit="1" punkte="9">P</Feld>
        <Feld id="F37" zeile="4" spalte="5" verwendbarkeit="1" punkte="0">☻</Feld>
        <Feld id="F38" zeile="4" spalte="6" verwendbarkeit="1" punkte="5">☺</Feld>
        <Feld id="F39" zeile="4" spalte="7" verwendbarkeit="1" punkte="4">☻</Feld>
        <Feld id="F40" zeile="5" spalte="0" verwendbarkeit="1" punkte="5">☺</Feld>
        <Feld id="F41" zeile="5" spalte="1" verwendbarkeit="1" punkte="0">☺</Feld>
        <Feld id="F42" zeile="5" spalte="2" verwendbarkeit="1" punkte="7">☺</Feld>
        <Feld id="F43" zeile="5" spalte="3" verwendbarkeit="1" punkte="7">☻</Feld>
        <Feld id="F44" zeile="5" spalte="4" verwendbarkeit="1" punkte="7">☆</Feld>
        <Feld id="F45" zeile="5" spalte="5" verwendbarkeit="1" punkte="2">R</Feld>
        <Feld id="F46" zeile="5" spalte="6" verwendbarkeit="1" punkte="0">☻</Feld>
        <Feld id="F47" zeile="5" spalte="7" verwendbarkeit="1" punkte="8">☺</Feld>
        <Feld id="F48" zeile="6" spalte="0" verwendbarkeit="1" punkte="0">⛈</Feld>
        <Feld id="F49" zeile="6" spalte="1" verwendbarkeit="1" punkte="7">☺</Feld>
        <Feld id="F50" zeile="6" spalte="2" verwendbarkeit="1" punkte="2">☻</Feld>
        <Feld id="F51" zeile="6" spalte="3" verwendbarkeit="1" punkte="3">♫</Feld>
        <Feld id="F52" zeile="6" spalte="4" verwendbarkeit="1" punkte="6">☺</Feld>
        <Feld id="F53" zeile="6" spalte="5" verwendbarkeit="1" punkte="5">P</Feld>
        <Feld id="F54" zeile="6" spalte="6" verwendbarkeit="1" punkte="6">☻</Feld>
        <Feld id="F55" zeile="6" spalte="7" verwendbarkeit="1" punkte="5">⛰</Feld>
        <Feld id="F56" zeile="7" spalte="0" verwendbarkeit="1" punkte="8">☻</Feld>
        <Feld id="F57" zeile="7" spalte="1" verwendbarkeit="1" punkte="9">☼</Feld>
        <Feld id="F58" zeile="7" spalte="2" verwendbarkeit="1" punkte="4">⛈</Feld>
        <Feld id="F59" zeile="7" spalte="3" verwendbarkeit="1" punkte="4">♥</Feld>
        <Feld id="F60" zeile="7" spalte="4" verwendbarkeit="1" punkte="0">R</Feld>
        <Feld id="F61" zeile="7" spalte="5" verwendbarkeit="1" punkte="1">☻</Feld>
        <Feld id="F62" zeile="7" spalte="6" verwendbarkeit="1" punkte="6">★</Feld>
        <Feld id="F63" zeile="7" spalte="7" verwendbarkeit="1" punkte="3">★</Feld>
    </Dschungel>
    <Schlangenarten>
        <Schlangenart id="A0" punkte="10" anzahl="1">
            <Zeichenkette>PR☻PR♥</Zeichenkette>
            <Nachbarschaftsstruktur typ="Distanz">
                <Parameter wert="1" />
            </Nachbarschaftsstruktur>
        </Schlangenart>
        <Schlangenart id="A1" punkte="10" anzahl="1">
            <Zeichenkette>PR☺PR♡</Zeichenkette>
            <Nachbarschaftsstruktur typ="Distanz">
                <Parameter wert="1" />
            </Nachbarschaftsstruktur>
        </Schlangenart>
        <Schlangenart id="A2" punkte="1" anzahl="6">
            <Zeichenkette>☺☻</Zeichenkette>
            <Nachbarschaftsstruktur typ="Distanz">
                <Parameter wert="1" />
            </Nachbarschaftsstruktur>
        </Schlangenart>
        <Schlangenart id="A3" punkte="3" anzahl="4">
            <Zeichenkette>☺☻☺☻</Zeichenkette>
            <Nachbarschaftsstruktur typ="Distanz">
                <Parameter wert="1" />
            </Nachbarschaftsstruktur>
        </Schlangenart>
        <Schlangenart id="A4" punkte="6" anzahl="2">
            <Zeichenkette>☺☻☺☻☺☻</Zeichenkette>
            <Nachbarschaftsstruktur typ="Distanz">
                <Parameter wert="1" />
            </Nachbarschaftsstruktur>
        </Schlangenart>
    </Schlangenarten>
    <Schlangen />
</Schlangenjagd>

=== nemouu/wordsnake-hunt/res/sj_p11_unvollstaendig.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Schlangenjagd SYSTEM "schlangenjagd.dtd" >
<Schlangenjagd>
	<Zeit einheit="s">
		<Vorgabe>10.0</Vorgabe>
	</Zeit>
	<Dschungel zeilen="7" spalten="7" zeichen="AEIOU">
	</Dschungel>
    <Schlangenarten>
        <Schlangenart id="A0" punkte="10" anzahl="1">
            <Zeichenkette>ADA</Zeichenkette>
            <Nachbarschaftsstruktur typ="Distanz">
                <Parameter wert="1" />
            </Nachbarschaftsstruktur>
        </Schlangenart>
        <Schlangenart id="A1" punkte="10" anzahl="1">
            <Zeichenkette>AMY</Zeichenkette>
            <Nachbarschaftsstruktur typ="Distanz">
                <Parameter wert="1" />
            </Nachbarschaftsstruktur>
        </Schlangenart>
        <Schlangenart id="A2" punkte="10" anzahl="1">
            <Zeichenkette>ANN</Zeichenkette>
            <Nachbarschaftsstruktur typ="Distanz">
                <Parameter wert="1" />
            </Nachbarschaftsstruktur>
        </Schlangenart>
        <Schlangenart id="A3" punkte="10" anzahl="1">
            <Zeichenkette>AVA</Zeichenkette>
            <Nachbarschaftsstruktur typ="Distanz">
                <Parameter wert="1" />
            </Nachbarschaftsstruktur>
        </Schlangenart>
        <Schlangenart id="A4" punkte="10" anzahl="1">
            <Zeichenkette>BEA</Zeichenkette>
            <Nachbarschaftsstruktur typ="Distanz">
                <Parameter wert="1" />
            </Nachbarschaftsstruktur>
        </Schlangenart>
        <Schlangenart id="A5" punkte="10" anzahl="1">
            <Zeichenkette>ELA</Zeichenkette>
            <Nachbarschaftsstruktur typ="Distanz">
                <Parameter wert="1" />
            </Nachbarschaftsstruktur>
        </Schlangenart>
        <Schlangenart id="A6" punkte="10" anzahl="1">
            <Zeichenkette>EVA</Zeichenkette>
            <Nachbarschaftsstruktur typ="Distanz">
                <Parameter wert="1" />
            </Nachbarschaftsstruktur>
        </Schlangenart>
        <Schlangenart id="A7" punkte="10" anzahl="1">
            <Zeichenkette>IDA</Zeichenkette>
            <Nachbarschaftsstruktur typ="Distanz">
                <Parameter wert="1" />
            </Nachbarschaftsstruktur>
        </Schlangenart>
        <Schlangenart id="A8" punkte="10" anzahl="1">
            <Zeichenkette>INA</Zeichenkette>
            <Nachbarschaftsstruktur typ="Distanz">
                <Parameter wert="1" />
            </Nachbarschaftsstruktur>
        </Schlangenart>
        <Schlangenart id="A9" punkte="10" anzahl="1">
            <Zeichenkette>ISA</Zeichenkette>
            <Nachbarschaftsstruktur typ="Distanz">
                <Parameter wert="1" />
            </Nachbarschaftsstruktur>
        </Schlangenart>
        <Schlangenart id="A10" punkte="10" anzahl="1">
            <Zeichenkette>LEA</Zeichenkette>
            <Nachbarschaftsstruktur typ="Distanz">
                <Parameter wert="1" />
            </Nachbarschaftsstruktur>
        </Schlangenart>
        <Schlangenart id="A11" punkte="10" anzahl="1">
            <Zeichenkette>LIA</Zeichenkette>
            <Nachbarschaftsstruktur typ="Distanz">
                <Parameter wert="1" />
            </Nachbarschaftsstruktur>
        </Schlangenart>
        <Schlangenart id="A12" punkte="10" anzahl="1">
            <Zeichenkette>LIN</Zeichenkette>
            <Nachbarschaftsstruktur typ="Distanz">
                <Parameter wert="1" />
            </Nachbarschaftsstruktur>
        </Schlangenart>
        <Schlangenart id="A13" punkte="10" anzahl="1">
            <Zeichenkette>LIV</Zeichenkette>
            <Nachbarschaftsstruktur typ="Distanz">
                <Parameter wert="1" />
            </Nachbarschaftsstruktur>
        </Schlangenart>
        <Schlangenart id="A14" punkte="10" anzahl="1">
            <Zeichenkette>MIA</Zeichenkette>
            <Nachbarschaftsstruktur typ="Distanz">
                <Parameter wert="1" />
            </Nachbarschaftsstruktur>
        </Schlangenart>
        <Schlangenart id="A15" punkte="10" anzahl="1">
            <Zeichenkette>PIA</Zeichenkette>
            <Nachbarschaftsstruktur typ="Distanz">
                <Parameter wert="1" />
            </Nachbarschaftsstruktur>
        </Schlangenart>
        <Schlangenart id="A16" punkte="10" anzahl="1">
            <Zeichenkette>RIA</Zeichenkette>
            <Nachbarschaftsstruktur typ="Distanz">
                <Parameter wert="1" />
            </Nachbarschaftsstruktur>
        </Schlangenart>
        <Schlangenart id="A17" punkte="10" anzahl="1">
            <Zeichenkette>SUE</Zeichenkette>
            <Nachbarschaftsstruktur typ="Distanz">
                <Parameter wert="1" />
            </Nachbarschaftsstruktur>
        </Schlangenart>
        <Schlangenart id="A18" punkte="10" anzahl="1">
            <Zeichenkette>UTE</Zeichenkette>
            <Nachbarschaftsstruktur typ="Distanz">
                <Parameter wert="1" />
            </Nachbarschaftsstruktur>
        </Schlangenart>
        <Schlangenart id="A19" punkte="10" anzahl="1">
            <Zeichenkette>ZOE</Zeichenkette>
            <Nachbarschaftsstruktur typ="Distanz">
                <Parameter wert="1" />
            </Nachbarschaftsstruktur>
        </Schlangenart>
    </Schlangenarten>
</Schlangenjagd>

=== nemouu/wordsnake-hunt/res/test_fuer_schreiben_in_einer_unvollstaendigen_datei.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Schlangenjagd SYSTEM "schlangenjagd.dtd">
<Schlangenjagd>
  <Zeit einheit="s">
    <Vorgabe>1.0</Vorgabe>
    <Abgabe>2.0</Abgabe>
  </Zeit>
  <Dschungel zeilen="2" spalten="3" zeichen="asdertg" />
  <Schlangenarten>
    <Schlangenart id="A0" punkte="1" anzahl="1">
      <Zeichenkette>abcdefghij</Zeichenkette>
      <Nachbarschaftsstruktur typ="Distanz">
        <Parameter wert="2" />
      </Nachbarschaftsstruktur>
    </Schlangenart>
    <Schlangenart id="A1" punkte="21" anzahl="31">
      <Zeichenkette>hjgzhi</Zeichenkette>
      <Nachbarschaftsstruktur typ="Distanz">
        <Parameter wert="2" />
      </Nachbarschaftsstruktur>
    </Schlangenart>
  </Schlangenarten>
</Schlangenjagd>

=== nemouu/wordsnake-hunt/res/sj_p7_probleminstanz_test.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Schlangenjagd SYSTEM "schlangenjagd.dtd">
<Schlangenjagd>
  <Zeit einheit="s">
    <Vorgabe>10.0</Vorgabe>
    <Abgabe>10.000012218</Abgabe>
  </Zeit>
  <Dschungel zeilen="10" spalten="5" zeichen="!&quot;§$%&amp;/()=?+*~#',;:-_@€&lt;&gt;|">
    <Feld id="F0" zeile="0" spalte="0" verwendbarkeit="1" punkte="5">N</Feld>
    <Feld id="F1" zeile="0" spalte="1" verwendbarkeit="1" punkte="8">a</Feld>
    <Feld id="F2" zeile="0" spalte="2" verwendbarkeit="1" punkte="7">e</Feld>
    <Feld id="F3" zeile="0" spalte="3" verwendbarkeit="1" punkte="3">h</Feld>
    <Feld id="F4" zeile="0" spalte="4" verwendbarkeit="1" punkte="4">;</Feld>
    <Feld id="F5" zeile="1" spalte="0" verwendbarkeit="1" punkte="4">N</Feld>
    <Feld id="F6" zeile="1" spalte="1" verwendbarkeit="1" punkte="4">H</Feld>
    <Feld id="F7" zeile="1" spalte="2" verwendbarkeit="1" punkte="6">G</Feld>
    <Feld id="F8" zeile="1" spalte="3" verwendbarkeit="1" punkte="8">g</Feld>
    <Feld id="F9" zeile="1" spalte="4" verwendbarkeit="1" punkte="8">E</Feld>
    <Feld id="F10" zeile="2" spalte="0" verwendbarkeit="1" punkte="9">E</Feld>
    <Feld id="F11" zeile="2" spalte="1" verwendbarkeit="1" punkte="3">A</Feld>
    <Feld id="F12" zeile="2" spalte="2" verwendbarkeit="1" punkte="7">N</Feld>
    <Feld id="F13" zeile="2" spalte="3" verwendbarkeit="1" punkte="3">G</Feld>
    <Feld id="F14" zeile="2" spalte="4" verwendbarkeit="1" punkte="2">e</Feld>
    <Feld id="F15" zeile="3" spalte="0" verwendbarkeit="1" punkte="4">N</Feld>
    <Feld id="F16" zeile="3" spalte="1" verwendbarkeit="1" punkte="2">n</Feld>
    <Feld id="F17" zeile="3" spalte="2" verwendbarkeit="1" punkte="2">A</Feld>
    <Feld id="F18" zeile="3" spalte="3" verwendbarkeit="1" punkte="6">A</Feld>
    <Feld id="F19" zeile="3" spalte="4" verwendbarkeit="1" punkte="9">h</Feld>
    <Feld id="F20" zeile="4" spalte="0" verwendbarkeit="1" punkte="6">G</Feld>
    <Feld id="F21" zeile="4" spalte="1" verwendbarkeit="1" punkte="2">e</Feld>
    <Feld id="F22" zeile="4" spalte="2" verwendbarkeit="1" punkte="0">e</Feld>
    <Feld id="F23" zeile="4" spalte="3" verwendbarkeit="1" punkte="9">G</Feld>
    <Feld id="F24" zeile="4" spalte="4" verwendbarkeit="1" punkte="4">!</Feld>
    <Feld id="F25" zeile="5" spalte="0" verwendbarkeit="1" punkte="9">N</Feld>
    <Feld id="F26" zeile="5" spalte="1" verwendbarkeit="1" punkte="8">G</Feld>
    <Feld id="F27" zeile="5" spalte="2" verwendbarkeit="1" punkte="3">g</Feld>
    <Feld id="F28" zeile="5" spalte="3" verwendbarkeit="1" punkte="7">H</Feld>
    <Feld id="F29" zeile="5" spalte="4" verwendbarkeit="1" punkte="2">H</Feld>
    <Feld id="F30" zeile="6" spalte="0" verwendbarkeit="1" punkte="5">(</Feld>
    <Feld id="F31" zeile="6" spalte="1" verwendbarkeit="1" punkte="4">e</Feld>
    <Feld id="F32" zeile="6" spalte="2" verwendbarkeit="1" punkte="0">=</Feld>
    <Feld id="F33" zeile="6" spalte="3" verwendbarkeit="1" punkte="6">n</Feld>
    <Feld id="F34" zeile="6" spalte="4" verwendbarkeit="1" punkte="3">e</Feld>
    <Feld id="F35" zeile="7" spalte="0" verwendbarkeit="1" punkte="5">a</Feld>
    <Feld id="F36" zeile="7" spalte="1" verwendbarkeit="1" punkte="9">h</Feld>
    <Feld id="F37" zeile="7" spalte="2" verwendbarkeit="1" punkte="0">N</Feld>
    <Feld id="F38" zeile="7" spalte="3" verwendbarkeit="1" punkte="5">*</Feld>
    <Feld id="F39" zeile="7" spalte="4" verwendbarkeit="1" punkte="4">a</Feld>
    <Feld id="F40" zeile="8" spalte="0" verwendbarkeit="1" punkte="5">&gt;</Feld>
    <Feld id="F41" zeile="8" spalte="1" verwendbarkeit="1" punkte="0">H</Feld>
    <Feld id="F42" zeile="8" spalte="2" verwendbarkeit="1" punkte="7">G</Feld>
    <Feld id="F43" zeile="8" spalte="3" verwendbarkeit="1" punkte="7">A</Feld>
    <Feld id="F44" zeile="8" spalte="4" verwendbarkeit="1" punkte="7">a</Feld>
    <Feld id="F45" zeile="9" spalte="0" verwendbarkeit="1" punkte="2">_</Feld>
    <Feld id="F46" zeile="9" spalte="1" verwendbarkeit="1" punkte="0">€</Feld>
    <Feld id="F47" zeile="9" spalte="2" verwendbarkeit="1" punkte="8">€</Feld>
    <Feld id="F48" zeile="9" spalte="3" verwendbarkeit="1" punkte="0">?</Feld>
    <Feld id="F49" zeile="9" spalte="4" verwendbarkeit="1" punkte="7">h</Feld>
  </Dschungel>
  <Schlangenarten>
    <Schlangenart id="A0" punkte="1" anzahl="2">
      <Zeichenkette>hagen</Zeichenkette>
      <Nachbarschaftsstruktur typ="Distanz">
        <Parameter wert="3" />
      </Nachbarschaftsstruktur>
    </Schlangenart>
    <Schlangenart id="A1" punkte="1" anzahl="2">
      <Zeichenkette>HAGEN</Zeichenkette>
      <Nachbarschaftsstruktur typ="Distanz">
        <Parameter wert="3" />
      </Nachbarschaftsstruktur>
    </Schlangenart>
    <Schlangenart id="A2" punkte="1" anzahl="2">
      <Zeichenkette>HaGeN</Zeichenkette>
      <Nachbarschaftsstruktur typ="Distanz">
        <Parameter wert="3" />
      </Nachbarschaftsstruktur>
    </Schlangenart>
    <Schlangenart id="A3" punkte="1" anzahl="2">
      <Zeichenkette>hAGeN</Zeichenkette>
      <Nachbarschaftsstruktur typ="Distanz">
        <Parameter wert="3" />
      </Nachbarschaftsstruktur>
    </Schlangenart>
  </Schlangenarten>
  <Schlangen>
    <Schlange art="A1">
      <Schlangenglied feld="F28" />
      <Schlangenglied feld="F43" />
      <Schlangenglied feld="F26" />
      <Schlangenglied feld="F10" />
      <Schlangenglied feld="F25" />
    </Schlange>
    <Schlange art="A0">
      <Schlangenglied feld="F19" />
      <Schlangenglied feld="F1" />
      <Schlangenglied feld="F8" />
      <Schlangenglied feld="F21" />
      <Schlangenglied feld="F33" />
    </Schlange>
    <Schlange art="A3">
      <Schlangenglied feld="F3" />
      <Schlangenglied feld="F18" />
      <Schlangenglied feld="F7" />
      <Schlangenglied feld="F2" />
      <Schlangenglied feld="F0" />
    </Schlange>
    <Schlange art="A1">
      <Schlangenglied feld="F6" />
      <Schlangenglied feld="F11" />
      <Schlangenglied feld="F23" />
      <Schlangenglied feld="F9" />
      <Schlangenglied feld="F12" />
    </Schlange>
    <Schlange art="A0">
      <Schlangenglied feld="F36" />
      <Schlangenglied feld="F44" />
      <Schlangenglied feld="F27" />
      <Schlangenglied feld="F34" />
      <Schlangenglied feld="F16" />
    </Schlange>
    <Schlange art="A2">
      <Schlangenglied feld="F29" />
      <Schlangenglied feld="F39" />
      <Schlangenglied feld="F42" />
      <Schlangenglied feld="F31" />
      <Schlangenglied feld="F15" />
    </Schlange>
    <Schlange art="A2">
      <Schlangenglied feld="F41" />
      <Schlangenglied feld="F35" />
      <Schlangenglied feld="F20" />
      <Schlangenglied feld="F22" />
      <Schlangenglied feld="F5" />
    </Schlange>
  </Schlangen>
</Schlangenjagd>
