=== nemouu/wordsnake-hunt/res/schlangenjagd.dtd
<!ELEMENT Schlangenjagd (Zeit?, Dschungel, Schlangenarten, 
        Schlangen?)>
<!ELEMENT Zeit (Vorgabe, Abgabe?)> 
<!ATTLIST Zeit
    einheit (ms|s|min|h|d) "s"
>
<!ELEMENT Vorgabe (#PCDATA)>
<!ELEMENT Abgabe (#PCDATA)>
<!ELEMENT Dschungel (Feld*)>
<!ATTLIST Dschungel
    zeilen CDATA #REQUIRED
    spalten CDATA #REQUIRED
    zeichen CDATA #REQUIRED
>
<!ELEMENT Feld (#PCDATA)> 
<!ATTLIST Feld
    id ID #REQUIRED
    zeile CDATA #REQUIRED
    spalte CDATA #REQUIRED
    verwendbarkeit CDATA "1"
    punkte CDATA "1"
>
<!ELEMENT Schlangenarten (Schlangenart+)>
<!ELEMENT Schlangenart (Zeichenkette, Nachbarschaftsstruktur)>
<!ATTLIST Schlangenart
    id ID #REQUIRED
    punkte CDATA "1"
    anzahl CDATA #REQUIRED
>
<!ELEMENT Zeichenkette (#PCDATA)>
<!ELEMENT Nachbarschaftsstruktur (Parameter*)>
<!ATTLIST Nachbarschaftsstruktur
    typ CDATA #REQUIRED
>
<!ELEMENT Parameter EMPTY>
<!ATTLIST Parameter
    wert CDATA #REQUIRED
>
<!ELEMENT Schlangen (Schlange*)>
<!ELEMENT Schlange (Schlangenglied+)>
<!ATTLIST Schlange
    art IDREF #REQUIRED
>
<!ELEMENT Schlangenglied EMPTY>
<!ATTLIST Schlangenglied
    feld IDREF #REQUIRED
>

=== nemouu/wordsnake-hunt/res/sj_p3_unvollstaendig.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Schlangenjagd SYSTEM "schlangenjagd.dtd" >
<Schlangenjagd>
	<Zeit einheit="s">
		<Vorgabe>10.0</Vorgabe>
	</Zeit>
	<Dschungel zeilen="11" spalten="11" zeichen="ABCDEFGHIJKLMNOPQRSTUVWXYZ">
	</Dschungel>
	<Schlangenarten>
		<Schlangenart id="A0" punkte="1" anzahl="1">
			<Zeichenkette>DONAUDAMPFSCHIFFFAHRTSELEKTRIZITĂ„TENHAUPTBETRIEBSWERKBAUUNTERBEAMTENGESELLSCHAFT</Zeichenkette>
			<Nachbarschaftsstruktur typ="Distanz">
				<Parameter wert="1" />
			</Nachbarschaftsstruktur>
		</Schlangenart>
	</Schlangenarten>
</Schlangenjagd>

=== nemouu/wordsnake-hunt/res/sj_p12_probleminstanz.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Schlangenjagd SYSTEM "schlangenjagd.dtd">
<Schlangenjagd>
    <Zeit einheit="s">
        <Vorgabe>10.0</Vorgabe>
    </Zeit>
    <Dschungel zeilen="5" spalten="5" zeichen="VIP">
        <Feld id="F0" zeile="0" spalte="0" verwendbarkeit="5" punkte="5">V</Feld>
        <Feld id="F1" zeile="0" spalte="1" verwendbarkeit="8" punkte="8">T</Feld>
        <Feld id="F2" zeile="0" spalte="2" verwendbarkeit="7" punkte="7">P</Feld>
        <Feld id="F3" zeile="0" spalte="3" verwendbarkeit="3" punkte="3">E</Feld>
        <Feld id="F4" zeile="0" spalte="4" verwendbarkeit="4" punkte="4">V</Feld>
        <Feld id="F5" zeile="1" spalte="0" verwendbarkeit="4" punkte="4">T</Feld>
        <Feld id="F6" zeile="1" spalte="1" verwendbarkeit="4" punkte="4">I</Feld>
        <Feld id="F7" zeile="1" spalte="2" verwendbarkeit="6" punkte="6">E</Feld>
        <Feld id="F8" zeile="1" spalte="3" verwendbarkeit="8" punkte="8">R</Feld>
        <Feld id="F9" zeile="1" spalte="4" verwendbarkeit="8" punkte="8">I</Feld>
        <Feld id="F10" zeile="2" spalte="0" verwendbarkeit="9" punkte="9">I</Feld>
        <Feld id="F11" zeile="2" spalte="1" verwendbarkeit="3" punkte="3">O</Feld>
        <Feld id="F12" zeile="2" spalte="2" verwendbarkeit="7" punkte="7">V</Feld>
        <Feld id="F13" zeile="2" spalte="3" verwendbarkeit="3" punkte="3">R</Feld>
        <Feld id="F14" zeile="2" spalte="4" verwendbarkeit="2" punkte="2">P</Feld>
        <Feld id="F15" zeile="3" spalte="0" verwendbarkeit="4" punkte="4">I</Feld>
        <Feld id="F16" zeile="3" spalte="1" verwendbarkeit="2" punkte="2">T</Feld>
        <Feld id="F17" zeile="3" spalte="2" verwendbarkeit="2" punkte="2">T</Feld>
        <Feld id="F18" zeile="3" spalte="3" verwendbarkeit="6" punkte="6">R</Feld>
        <Feld id="F19" zeile="3" spalte="4" verwendbarkeit="9" punkte="9">P</Feld>
        <Feld id="F20" zeile="4" spalte="0" verwendbarkeit="6" punkte="6">N</Feld>
        <Feld id="F21" zeile="4" spalte="1" verwendbarkeit="2" punkte="2">A</Feld>
        <Feld id="F22" zeile="4" spalte="2" verwendbarkeit="0" punkte="0">E</Feld>
        <Feld id="F23" zeile="4" spalte="3" verwendbarkeit="9" punkte="9">I</Feld>
        <Feld id="F24" zeile="4" spalte="4" verwendbarkeit="4" punkte="4">I</Feld>
    </Dschungel>
    <Schlangenarten>
        <Schlangenart id="A0" punkte="100" anzahl="1">
            <Zeichenkette>NATTER</Zeichenkette>
            <Nachbarschaftsstruktur typ="Distanz">
                <Parameter wert="1" />
            </Nachbarschaftsstruktur>
        </Schlangenart>
        <Schlangenart id="A1" punkte="10" anzahl="1">
            <Zeichenkette>OTTER</Zeichenkette>
            <Nachbarschaftsstruktur typ="Distanz">
                <Parameter wert="1" />
            </Nachbarschaftsstruktur>
        </Schlangenart>
        <Schlangenart id="A2" punkte="1" anzahl="1">
            <Zeichenkette>VIPER</Zeichenkette>
            <Nachbarschaftsstruktur typ="Distanz">
                <Parameter wert="1" />
            </Nachbarschaftsstruktur>
        </Schlangenart>
    </Schlangenarten>
    <Schlangen />
</Schlangenjagd>

=== nemouu/wordsnake-hunt/res/sj_p8_unvollstaendig.xml
<?xml version="1.1" encoding="UTF-8"?>
<!DOCTYPE Schlangenjagd SYSTEM "schlangenjagd.dtd" >
<Schlangenjagd>
	<Zeit einheit="min">
		<Vorgabe>0.2</Vorgabe>
	</Zeit>
	<Dschungel zeilen="8" spalten="8" zeichen="☀☁☂☃☄★☆☇☔☕☼☽☾♨♫⚘⚽⛄⛅⛆⛈⛐⛰⛵⛷⛸⛹⛺">
	</Dschungel>
	<Schlangenarten>
		<Schlangenart id="A0" punkte="10" anzahl="1">
			<Zeichenkette>PR☻PR♥</Zeichenkette>
			<Nachbarschaftsstruktur typ="Distanz">
				<Parameter wert="1" />
			</Nachbarschaftsstruktur>
		</Schlangenart>
		<Schlangenart id="A1" punkte="10" anzahl="1">
			<Zeichenkette>PR☺PR♡</Zeichenkette>
			<Nachbarschaftsstruktur typ="Distanz">
				<Parameter wert="1" />
			</Nachbarschaftsstruktur>
		</Schlangenart>
		<Schlangenart id="A2" punkte="1" anzahl="6">
			<Zeichenkette>☺☻</Zeichenkette>
			<Nachbarschaftsstruktur typ="Distanz">
				<Parameter wert="1" />
			</Nachbarschaftsstruktur>
		</Schlangenart>
		<Schlangenart id="A3" punkte="3" anzahl="4">
			<Zeichenkette>☺☻☺☻</Zeichenkette>
			<Nachbarschaftsstruktur typ="Distanz">
				<Parameter wert="1" />
			</Nachbarschaftsstruktur>
		</Schlangenart>
		<Schlangenart id="A4" punkte="6" anzahl="2">
			<Zeichenkette>☺☻☺☻☺☻</Zeichenkette>
			<Nachbarschaftsstruktur typ="Distanz">
				<Parameter wert="1" />
			</Nachbarschaftsstruktur>
		</Schlangenart>
	</Schlangenarten>
</Schlangenjagd>

=== nemouu/wordsnake-hunt/res/sj_p10_probleminstanz.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Schlangenjagd SYSTEM "schlangenjagd.dtd">
<Schlangenjagd>
    <Zeit einheit="d">
        <Vorgabe>2.0E-4</Vorgabe>
    </Zeit>
    <Dschungel zeilen="6" spalten="6" zeichen="BELN">
        <Feld id="F0" zeile="0" spalte="0" verwendbarkeit="1" punkte="5">L</Feld>
        <Feld id="F1" zeile="0" spalte="1" verwendbarkeit="1" punkte="8">N</Feld>
        <Feld id="F2" zeile="0" spalte="2" verwendbarkeit="1" punkte="7">B</Feld>
        <Feld id="F3" zeile="0" spalte="3" verwendbarkeit="1" punkte="3">E</Feld>
        <Feld id="F4" zeile="0" spalte="4" verwendbarkeit="1" punkte="4">E</Feld>
        <Feld id="F5" zeile="0" spalte="5" verwendbarkeit="1" punkte="4">L</Feld>
        <Feld id="F6" zeile="1" spalte="0" verwendbarkeit="1" punkte="4">E</Feld>
        <Feld id="F7" zeile="1" spalte="1" verwendbarkeit="1" punkte="6">E</Feld>
        <Feld id="F8" zeile="1" spalte="2" verwendbarkeit="1" punkte="8">B</Feld>
        <Feld id="F9" zeile="1" spalte="3" verwendbarkeit="1" punkte="8">B</Feld>
        <Feld id="F10" zeile="1" spalte="4" verwendbarkeit="1" punkte="9">B</Feld>
        <Feld id="F11" zeile="1" spalte="5" verwendbarkeit="1" punkte="3">E</Feld>
        <Feld id="F12" zeile="2" spalte="0" verwendbarkeit="1" punkte="7">L</Feld>
        <Feld id="F13" zeile="2" spalte="1" verwendbarkeit="1" punkte="3">L</Feld>
        <Feld id="F14" zeile="2" spalte="2" verwendbarkeit="1" punkte="2">N</Feld>
        <Feld id="F15" zeile="2" spalte="3" verwendbarkeit="1" punkte="4">E</Feld>
        <Feld id="F16" zeile="2" spalte="4" verwendbarkeit="1" punkte="2">N</Feld>
        <Feld id="F17" zeile="2" spalte="5" verwendbarkeit="1" punkte="2">L</Feld>
        <Feld id="F18" zeile="3" spalte="0" verwendbarkeit="1" punkte="6">B</Feld>
        <Feld id="F19" zeile="3" spalte="1" verwendbarkeit="1" punkte="9">E</Feld>
        <Feld id="F20" zeile="3" spalte="2" verwendbarkeit="1" punkte="6">E</Feld>
        <Feld id="F21" zeile="3" spalte="3" verwendbarkeit="1" punkte="2">B</Feld>
        <Feld id="F22" zeile="3" spalte="4" verwendbarkeit="1" punkte="0">L</Feld>
        <Feld id="F23" zeile="3" spalte="5" verwendbarkeit="1" punkte="9">B</Feld>
        <Feld id="F24" zeile="4" spalte="0" verwendbarkeit="1" punkte="4">B</Feld>
        <Feld id="F25" zeile="4" spalte="1" verwendbarkeit="1" punkte="9">N</Feld>
        <Feld id="F26" zeile="4" spalte="2" verwendbarkeit="1" punkte="8">N</Feld>
        <Feld id="F27" zeile="4" spalte="3" verwendbarkeit="1" punkte="3">E</Feld>
        <Feld id="F28" zeile="4" spalte="4" verwendbarkeit="1" punkte="7">E</Feld>
        <Feld id="F29" zeile="4" spalte="5" verwendbarkeit="1" punkte="2">B</Feld>
        <Feld id="F30" zeile="5" spalte="0" verwendbarkeit="1" punkte="5">N</Feld>
        <Feld id="F31" zeile="5" spalte="1" verwendbarkeit="1" punkte="4">L</Feld>
        <Feld id="F32" zeile="5" spalte="2" verwendbarkeit="1" punkte="0">L</Feld>
        <Feld id="F33" zeile="5" spalte="3" verwendbarkeit="1" punkte="6">B</Feld>
        <Feld id="F34" zeile="5" spalte="4" verwendbarkeit="1" punkte="3">N</Feld>
        <Feld id="F35" zeile="5" spalte="5" verwendbarkeit="1" punkte="5">E</Feld>
    </Dschungel>
    <Schlangenarten>
        <Schlangenart id="A0" punkte="20" anzahl="2">
            <Zeichenkette>LEBEN</Zeichenkette>
            <Nachbarschaftsstruktur typ="Distanz">
                <Parameter wert="2" />
            </Nachbarschaftsstruktur>
        </Schlangenart>
        <Schlangenart id="A1" punkte="1" anzahl="2">
            <Zeichenkette>NEBEL</Zeichenkette>
            <Nachbarschaftsstruktur typ="Distanz">
                <Parameter wert="3" />
            </Nachbarschaftsstruktur>
        </Schlangenart>
    </Schlangenarten>
    <Schlangen />
</Schlangenjagd>

=== nemouu/wordsnake-hunt/res/sj_p1_unvollstaendig_einfach_test.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Schlangenjagd SYSTEM "schlangenjagd.dtd">
<Schlangenjagd>
  <Zeit einheit="s">
    <Vorgabe>60.0</Vorgabe>
  </Zeit>
  <Dschungel zeilen="2" spalten="4" zeichen="ABCDEFGHIJKLMNOPQRSTUVWXYZ">
    <Feld id="F0" zeile="0" spalte="0" verwendbarkeit="1" punkte="1">F</Feld>
    <Feld id="F1" zeile="0" spalte="1" verwendbarkeit="1" punkte="1">N</Feld>
    <Feld id="F2" zeile="0" spalte="2" verwendbarkeit="1" punkte="1">U</Feld>
    <Feld id="F3" zeile="0" spalte="3" verwendbarkeit="1" punkte="1">N</Feld>
    <Feld id="F4" zeile="1" spalte="0" verwendbarkeit="1" punkte="1">R</Feld>
    <Feld id="F5" zeile="1" spalte="1" verwendbarkeit="1" punkte="1">E</Feld>
    <Feld id="F6" zeile="1" spalte="2" verwendbarkeit="1" punkte="1">F</Feld>
    <Feld id="F7" zeile="1" spalte="3" verwendbarkeit="1" punkte="1">I</Feld>
  </Dschungel>
  <Schlangenarten>
    <Schlangenart id="A0" punkte="1" anzahl="1">
      <Zeichenkette>FERNUNI</Zeichenkette>
      <Nachbarschaftsstruktur typ="Distanz">
        <Parameter wert="1" />
      </Nachbarschaftsstruktur>
    </Schlangenart>
  </Schlangenarten>
</Schlangenjagd>

=== nemouu/wordsnake-hunt/res/sj_p2_loesung.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Schlangenjagd SYSTEM "schlangenjagd.dtd">
<Schlangenjagd>
    <Zeit einheit="s">
        <Vorgabe>10.0</Vorgabe>
        <Abgabe>10.000001284000001</Abgabe>
    </Zeit>
    <Dschungel zeilen="5" spalten="10" zeichen="ABCDEFGHIJKLMNOPQRSTUVWXYZ">
        <Feld id="F0" zeile="0" spalte="0" verwendbarkeit="1" punkte="1">I</Feld>
        <Feld id="F1" zeile="0" spalte="1" verwendbarkeit="1" punkte="1">D</Feld>
        <Feld id="F2" zeile="0" spalte="2" verwendbarkeit="1" punkte="1">R</Feld>
        <Feld id="F3" zeile="0" spalte="3" verwendbarkeit="1" punkte="1">A</Feld>
        <Feld id="F4" zeile="0" spalte="4" verwendbarkeit="1" punkte="1">S</Feld>
        <Feld id="F5" zeile="0" spalte="5" verwendbarkeit="1" punkte="1">S</Feld>
        <Feld id="F6" zeile="0" spalte="6" verwendbarkeit="1" punkte="1">H</Feld>
        <Feld id="F7" zeile="0" spalte="7" verwendbarkeit="1" punkte="1">I</Feld>
        <Feld id="F8" zeile="0" spalte="8" verwendbarkeit="1" punkte="1">D</Feld>
        <Feld id="F9" zeile="0" spalte="9" verwendbarkeit="1" punkte="1">J</Feld>
        <Feld id="F10" zeile="1" spalte="0" verwendbarkeit="1" punkte="1">E</Feld>
        <Feld id="F11" zeile="1" spalte="1" verwendbarkeit="1" punkte="1">D</Feld>
        <Feld id="F12" zeile="1" spalte="2" verwendbarkeit="1" punkte="1">M</Feld>
        <Feld id="F13" zeile="1" spalte="3" verwendbarkeit="1" punkte="1">E</Feld>
        <Feld id="F14" zeile="1" spalte="4" verwendbarkeit="1" punkte="1">E</Feld>
        <Feld id="F15" zeile="1" spalte="5" verwendbarkeit="1" punkte="1">Y</Feld>
        <Feld id="F16" zeile="1" spalte="6" verwendbarkeit="1" punkte="1">E</Feld>
        <Feld id="F17" zeile="1" spalte="7" verwendbarkeit="1" punkte="1">I</Feld>
        <Feld id="F18" zeile="1" spalte="8" verwendbarkeit="1" punkte="1">U</Feld>
        <Feld id="F19" zeile="1" spalte="9" verwendbarkeit="1" punkte="1">W</Feld>
        <Feld id="F20" zeile="2" spalte="0" verwendbarkeit="1" punkte="1">S</Feld>
        <Feld id="F21" zeile="2" spalte="1" verwendbarkeit="1" punkte="1">E</Feld>
        <Feld id="F22" zeile="2" spalte="2" verwendbarkeit="1" punkte="1">I</Feld>
        <Feld id="F23" zeile="2" spalte="3" verwendbarkeit="1" punkte="1">S</Feld>
        <Feld id="F24" zeile="2" spalte="4" verwendbarkeit="1" punkte="1">W</Feld>
        <Feld id="F25" zeile="2" spalte="5" verwendbarkeit="1" punkte="1">K</Feld>
        <Feld id="F26" zeile="2" spalte="6" verwendbarkeit="1" punkte="1">E</Feld>
        <Feld id="F27" zeile="2" spalte="7" verwendbarkeit="1" punkte="1">D</Feld>
        <Feld id="F28" zeile="2" spalte="8" verwendbarkeit="1" punkte="1">R</Feld>
        <Feld id="F29" zeile="2" spalte="9" verwendbarkeit="1" punkte="1">X</Feld>
        <Feld id="F30" zeile="3" spalte="0" verwendbarkeit="1" punkte="1">E</Feld>
        <Feld id="F31" zeile="3" spalte="1" verwendbarkeit="1" punkte="1">I</Feld>
        <Feld id="F32" zeile="3" spalte="2" verwendbarkeit="1" punkte="1">I</Feld>
        <Feld id="F33" zeile="3" spalte="3" verwendbarkeit="1" punkte="1">N</Feld>
        <Feld id="F34" zeile="3" spalte="4" verwendbarkeit="1" punkte="1">N</Feld>
        <Feld id="F35" zeile="3" spalte="5" verwendbarkeit="1" punkte="1">F</Feld>
        <Feld id="F36" zeile="3" spalte="6" verwendbarkeit="1" punkte="1">E</Feld>
        <Feld id="F37" zeile="3" spalte="7" verwendbarkeit="1" punkte="1">S</Feld>
        <Feld id="F38" zeile="3" spalte="8" verwendbarkeit="1" punkte="1">M</Feld>
        <Feld id="F39" zeile="3" spalte="9" verwendbarkeit="1" punkte="1">Q</Feld>
        <Feld id="F40" zeile="4" spalte="0" verwendbarkeit="1" punkte="1">G</Feld>
        <Feld id="F41" zeile="4" spalte="1" verwendbarkeit="1" punkte="1">D</Feld>
        <Feld id="F42" zeile="4" spalte="2" verwendbarkeit="1" punkte="1">D</Feld>
        <Feld id="F43" zeile="4" spalte="3" verwendbarkeit="1" punkte="1">E</Feld>
        <Feld id="F44" zeile="4" spalte="4" verwendbarkeit="1" punkte="1">S</Feld>
        <Feld id="F45" zeile="4" spalte="5" verwendbarkeit="1" punkte="1">E</Feld>
        <Feld id="F46" zeile="4" spalte="6" verwendbarkeit="1" punkte="1">R</Feld>
        <Feld id="F47" zeile="4" spalte="7" verwendbarkeit="1" punkte="1">E</Feld>
        <Feld id="F48" zeile="4" spalte="8" verwendbarkeit="1" punkte="1">E</Feld>
        <Feld id="F49" zeile="4" spalte="9" verwendbarkeit="1" punkte="1">B</Feld>
    </Dschungel>
    <Schlangenarten>
        <Schlangenart id="A0" punkte="1" anzahl="1">
            <Zeichenkette>DIE</Zeichenkette>
            <Nachbarschaftsstruktur typ="Distanz">
                <Parameter wert="1" />
            </Nachbarschaftsstruktur>
        </Schlangenart>
        <Schlangenart id="A1" punkte="1" anzahl="1">
            <Zeichenkette>DIES</Zeichenkette>
            <Nachbarschaftsstruktur typ="Distanz">
                <Parameter wert="1" />
            </Nachbarschaftsstruktur>
        </Schlangenart>
        <Schlangenart id="A2" punkte="1" anzahl="1">
            <Zeichenkette>DIESE</Zeichenkette>
            <Nachbarschaftsstruktur typ="Distanz">
                <Parameter wert="1" />
            </Nachbarschaftsstruktur>
        </Schlangenart>
        <Schlangenart id="A3" punkte="1" anzahl="1">
            <Zeichenkette>DIESES</Zeichenkette>
            <Nachbarschaftsstruktur typ="Distanz">
                <Parameter wert="1" />
            </Nachbarschaftsstruktur>
        </Schlangenart>
        <Schlangenart id="A4" punkte="1" anzahl="1">
            <Zeichenkette>DIESEN</Zeichenkette>
            <Nachbarschaftsstruktur typ="Distanz">
                <Parameter wert="1" />
            </Nachbarschaftsstruktur>
        </Schlangenart>
        <Schlangenart id="A5" punkte="1" anzahl="1">
            <Zeichenkette>DIESER</Zeichenkette>
            <Nachbarschaftsstruktur typ="Distanz">
                <Parameter wert="1" />
            </Nachbarschaftsstruktur>
        </Schlangenart>
    </Schlangenarten>
    <Schlangen>
        <Schlange art="A0">
            <Schlangenglied feld="F1" />
            <Schlangenglied feld="F0" />
            <Schlangenglied feld="F10" />
        </Schlange>
        <Schlange art="A1">
            <Schlangenglied feld="F8" />
            <Schlangenglied feld="F7" />
            <Schlangenglied feld="F16" />
            <Schlangenglied feld="F5" />
        </Schlange>
        <Schlange art="A2">
            <Schlangenglied feld="F41" />
            <Schlangenglied feld="F31" />
            <Schlangenglied feld="F21" />
            <Schlangenglied feld="F20" />
            <Schlangenglied feld="F30" />
        </Schlange>
        <Schlange art="A3">
            <Schlangenglied feld="F11" />
            <Schlangenglied feld="F22" />
            <Schlangenglied feld="F13" />
            <Schlangenglied feld="F4" />
            <Schlangenglied feld="F14" />
            <Schlangenglied feld="F23" />
        </Schlange>
        <Schlange art="A4">
            <Schlangenglied feld="F42" />
            <Schlangenglied feld="F32" />
            <Schlangenglied feld="F43" />
            <Schlangenglied feld="F44" />
            <Schlangenglied feld="F45" />
            <Schlangenglied feld="F34" />
        </Schlange>
        <Schlange art="A5">
            <Schlangenglied feld="F27" />
            <Schlangenglied feld="F17" />
            <Schlangenglied feld="F26" />
            <Schlangenglied feld="F37" />
            <Schlangenglied feld="F36" />
            <Schlangenglied feld="F46" />
        </Schlange>
    </Schlangen>
</Schlangenjagd>

=== nemouu/wordsnake-hunt/res/sj_p7_unvollstaendig.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Schlangenjagd SYSTEM "schlangenjagd.dtd" >
<Schlangenjagd>
	<Zeit einheit="s">
		<Vorgabe>10.0</Vorgabe>
	</Zeit>
	<Dschungel zeilen="10" spalten="5" zeichen="!&quot;§$%&amp;/()=?+*~#',;:-_@€&lt;&gt;|">
	</Dschungel>
	<Schlangenarten>
		<Schlangenart id="A0" punkte="1" anzahl="2">
			<Zeichenkette>hagen</Zeichenkette>
			<Nachbarschaftsstruktur typ="Distanz">
				<Parameter wert="3" />
			</Nachbarschaftsstruktur>
		</Schlangenart>
		<Schlangenart id="A1" punkte="1" anzahl="2">
			<Zeichenkette>HAGEN</Zeichenkette>
			<Nachbarschaftsstruktur typ="Distanz">
				<Parameter wert="3" />
			</Nachbarschaftsstruktur>
		</Schlangenart>
		<Schlangenart id="A2" punkte="1" anzahl="2">
			<Zeichenkette>HaGeN</Zeichenkette>
			<Nachbarschaftsstruktur typ="Distanz">
				<Parameter wert="3" />
			</Nachbarschaftsstruktur>
		</Schlangenart>
		<Schlangenart id="A3" punkte="1" anzahl="2">
			<Zeichenkette>hAGeN</Zeichenkette>
			<Nachbarschaftsstruktur typ="Distanz">
				<Parameter wert="3" />
			</Nachbarschaftsstruktur>
		</Schlangenart>
	</Schlangenarten>
</Schlangenjagd>

=== nemouu/wordsnake-hunt/res/test_fuer_schreiben_in_probleminstanzdatei.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Schlangenjagd SYSTEM "schlangenjagd.dtd">
<Schlangenjagd>
  <Zeit einheit="s">
    <Vorgabe>1.0</Vorgabe>
    <Abgabe>2.0</Abgabe>
  </Zeit>
  <Dschungel zeilen="2" spalten="3" zeichen="asdertg">
    <Feld id="F0" zeile="0" spalte="0" verwendbarkeit="1" punkte="1">a0</Feld>
    <Feld id="F2" zeile="0" spalte="1" verwendbarkeit="1" punkte="1">a2</Feld>
    <Feld id="F4" zeile="0" spalte="2" verwendbarkeit="1" punkte="1">a4</Feld>
    <Feld id="F1" zeile="1" spalte="0" verwendbarkeit="1" punkte="1">a1</Feld>
    <Feld id="F3" zeile="1" spalte="1" verwendbarkeit="1" punkte="1">a3</Feld>
    <Feld id="F5" zeile="1" spalte="2" verwendbarkeit="1" punkte="1">a5</Feld>
  </Dschungel>
  <Schlangenarten>
    <Schlangenart id="A0" punkte="1" anzahl="1">
      <Zeichenkette>abcdefghij</Zeichenkette>
      <Nachbarschaftsstruktur typ="Distanz">
        <Parameter wert="2" />
      </Nachbarschaftsstruktur>
    </Schlangenart>
    <Schlangenart id="A1" punkte="21" anzahl="31">
      <Zeichenkette>hjgzhi</Zeichenkette>
      <Nachbarschaftsstruktur typ="Distanz">
        <Parameter wert="2" />
      </Nachbarschaftsstruktur>
    </Schlangenart>
  </Schlangenarten>
</Schlangenjagd>
