=== nemouu/wordsnake-hunt/res/snakehunt.dtd
<!ELEMENT SnakeHunt (Time?, Jungle, SnakeTypes, 
        Snakes?)>
<!ELEMENT Time (Limit, Elapsed?)> 
<!ATTLIST Time
    unit (ms|s|min|h|d) "s"
>
<!ELEMENT Limit (#PCDATA)>
<!ELEMENT Elapsed (#PCDATA)>
<!ELEMENT Jungle (Field*)>
<!ATTLIST Jungle
    rows CDATA #REQUIRED
    cols CDATA #REQUIRED
    signs CDATA #REQUIRED
>
<!ELEMENT Field (#PCDATA)> 
<!ATTLIST Field
    id ID #REQUIRED
    row CDATA #REQUIRED
    col CDATA #REQUIRED
    usability CDATA "1"
    points CDATA "1"
>
<!ELEMENT SnakeTypes (SnakeType+)>
<!ELEMENT SnakeType (Word, NeighborhoodStructure)>
<!ATTLIST SnakeType
    id ID #REQUIRED
    points CDATA "1"
    amount CDATA #REQUIRED
>
<!ELEMENT Word (#PCDATA)>
<!ELEMENT NeighborhoodStructure (Parameter*)>
<!ATTLIST NeighborhoodStructure
    type CDATA #REQUIRED
>
<!ELEMENT Parameter EMPTY>
<!ATTLIST Parameter
    value CDATA #REQUIRED
>
<!ELEMENT Snakes (Snake*)>
<!ELEMENT Snake (SnakeElement+)>
<!ATTLIST Snake
    type IDREF #REQUIRED
>
<!ELEMENT SnakeElement EMPTY>
<!ATTLIST SnakeElement
    field IDREF #REQUIRED
>

=== nemouu/wordsnake-hunt/res/sh_p6_problem_instance_test.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE SnakeHunt SYSTEM "snakehunt.dtd">
<SnakeHunt>
  <Time unit="ms">
    <Limit>2000.0</Limit>
    <Elapsed>2000.009816</Elapsed>
  </Time>
  <Jungle rows="6" cols="6" signs="X">
    <Field id="F0" row="0" col="0" usability="1" points="5">A</Field>
    <Field id="F1" row="0" col="1" usability="1" points="8">A</Field>
    <Field id="F2" row="0" col="2" usability="1" points="7">X</Field>
    <Field id="F3" row="0" col="3" usability="1" points="3">A</Field>
    <Field id="F4" row="0" col="4" usability="1" points="4">A</Field>
    <Field id="F5" row="0" col="5" usability="1" points="4">X</Field>
    <Field id="F6" row="1" col="0" usability="1" points="4">A</Field>
    <Field id="F7" row="1" col="1" usability="1" points="6">A</Field>
    <Field id="F8" row="1" col="2" usability="1" points="8">A</Field>
    <Field id="F9" row="1" col="3" usability="1" points="8">A</Field>
    <Field id="F10" row="1" col="4" usability="1" points="9">X</Field>
    <Field id="F11" row="1" col="5" usability="1" points="3">X</Field>
    <Field id="F12" row="2" col="0" usability="1" points="7">A</Field>
    <Field id="F13" row="2" col="1" usability="1" points="3">X</Field>
    <Field id="F14" row="2" col="2" usability="1" points="2">A</Field>
    <Field id="F15" row="2" col="3" usability="1" points="4">X</Field>
    <Field id="F16" row="2" col="4" usability="1" points="2">X</Field>
    <Field id="F17" row="2" col="5" usability="1" points="2">X</Field>
    <Field id="F18" row="3" col="0" usability="1" points="6">A</Field>
    <Field id="F19" row="3" col="1" usability="1" points="9">A</Field>
    <Field id="F20" row="3" col="2" usability="1" points="6">A</Field>
    <Field id="F21" row="3" col="3" usability="1" points="2">A</Field>
    <Field id="F22" row="3" col="4" usability="1" points="0">A</Field>
    <Field id="F23" row="3" col="5" usability="1" points="9">X</Field>
    <Field id="F24" row="4" col="0" usability="1" points="4">A</Field>
    <Field id="F25" row="4" col="1" usability="1" points="9">X</Field>
    <Field id="F26" row="4" col="2" usability="1" points="8">A</Field>
    <Field id="F27" row="4" col="3" usability="1" points="3">A</Field>
    <Field id="F28" row="4" col="4" usability="1" points="7">X</Field>
    <Field id="F29" row="4" col="5" usability="1" points="2">A</Field>
    <Field id="F30" row="5" col="0" usability="1" points="5">X</Field>
    <Field id="F31" row="5" col="1" usability="1" points="4">A</Field>
    <Field id="F32" row="5" col="2" usability="1" points="0">X</Field>
    <Field id="F33" row="5" col="3" usability="1" points="6">A</Field>
    <Field id="F34" row="5" col="4" usability="1" points="3">A</Field>
    <Field id="F35" row="5" col="5" usability="1" points="5">X</Field>
  </Jungle>
  <SnakeTypes>
    <SnakeType id="A0" points="1" amount="2">
      <Word>AA</Word>
      <NeighborhoodStructure type="Distance">
        <Parameter value="1" />
      </NeighborhoodStructure>
    </SnakeType>
    <SnakeType id="A1" points="5" amount="2">
      <Word>AA</Word>
      <NeighborhoodStructure type="Jump">
        <Parameter value="1" />
        <Parameter value="0" />
      </NeighborhoodStructure>
    </SnakeType>
    <SnakeType id="A2" points="5" amount="2">
      <Word>AA</Word>
      <NeighborhoodStructure type="Jump">
        <Parameter value="1" />
        <Parameter value="1" />
      </NeighborhoodStructure>
    </SnakeType>
    <SnakeType id="A3" points="10" amount="2">
      <Word>AA</Word>
      <NeighborhoodStructure type="Jump">
        <Parameter value="2" />
        <Parameter value="1" />
      </NeighborhoodStructure>
    </SnakeType>
    <SnakeType id="A4" points="100" amount="2">
      <Word>AAA</Word>
      <NeighborhoodStructure type="Jump">
        <Parameter value="3" />
        <Parameter value="1" />
      </NeighborhoodStructure>
    </SnakeType>
  </SnakeTypes>
  <Snakes>
    <Snake type="A4">
      <SnakeElement field="F19" />
      <SnakeElement field="F0" />
      <SnakeElement field="F9" />
    </Snake>
    <Snake type="A4">
      <SnakeElement field="F12" />
      <SnakeElement field="F31" />
      <SnakeElement field="F14" />
    </Snake>
    <Snake type="A4">
      <SnakeElement field="F33" />
      <SnakeElement field="F24" />
      <SnakeElement field="F21" />
    </Snake>
    <Snake type="A4">
      <SnakeElement field="F4" />
      <SnakeElement field="F7" />
      <SnakeElement field="F26" />
    </Snake>
    <Snake type="A4">
      <SnakeElement field="F1" />
      <SnakeElement field="F20" />
      <SnakeElement field="F29" />
    </Snake>
    <Snake type="A4">
      <SnakeElement field="F18" />
      <SnakeElement field="F27" />
      <SnakeElement field="F8" />
    </Snake>
    <Snake type="A4">
      <SnakeElement field="F6" />
      <SnakeElement field="F3" />
      <SnakeElement field="F22" />
    </Snake>
  </Snakes>
</SnakeHunt>

=== nemouu/wordsnake-hunt/res/sh_p2_problem_instance.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE SnakeHunt SYSTEM "snakehunt.dtd">
<SnakeHunt>
    <Time unit="s">
        <Limit>10.0</Limit>
    </Time>
    <Jungle rows="5" cols="10" signs="ABCDEFGHIJKLMNOPQRSTUVWXYZ">
        <Field id="F0" row="0" col="0" usability="1" points="1">I</Field>
        <Field id="F1" row="0" col="1" usability="1" points="1">D</Field>
        <Field id="F2" row="0" col="2" usability="1" points="1">R</Field>
        <Field id="F3" row="0" col="3" usability="1" points="1">A</Field>
        <Field id="F4" row="0" col="4" usability="1" points="1">S</Field>
        <Field id="F5" row="0" col="5" usability="1" points="1">S</Field>
        <Field id="F6" row="0" col="6" usability="1" points="1">H</Field>
        <Field id="F7" row="0" col="7" usability="1" points="1">I</Field>
        <Field id="F8" row="0" col="8" usability="1" points="1">D</Field>
        <Field id="F9" row="0" col="9" usability="1" points="1">J</Field>
        <Field id="F10" row="1" col="0" usability="1" points="1">E</Field>
        <Field id="F11" row="1" col="1" usability="1" points="1">D</Field>
        <Field id="F12" row="1" col="2" usability="1" points="1">M</Field>
        <Field id="F13" row="1" col="3" usability="1" points="1">E</Field>
        <Field id="F14" row="1" col="4" usability="1" points="1">E</Field>
        <Field id="F15" row="1" col="5" usability="1" points="1">Y</Field>
        <Field id="F16" row="1" col="6" usability="1" points="1">E</Field>
        <Field id="F17" row="1" col="7" usability="1" points="1">I</Field>
        <Field id="F18" row="1" col="8" usability="1" points="1">U</Field>
        <Field id="F19" row="1" col="9" usability="1" points="1">W</Field>
        <Field id="F20" row="2" col="0" usability="1" points="1">S</Field>
        <Field id="F21" row="2" col="1" usability="1" points="1">E</Field>
        <Field id="F22" row="2" col="2" usability="1" points="1">I</Field>
        <Field id="F23" row="2" col="3" usability="1" points="1">S</Field>
        <Field id="F24" row="2" col="4" usability="1" points="1">W</Field>
        <Field id="F25" row="2" col="5" usability="1" points="1">K</Field>
        <Field id="F26" row="2" col="6" usability="1" points="1">E</Field>
        <Field id="F27" row="2" col="7" usability="1" points="1">D</Field>
        <Field id="F28" row="2" col="8" usability="1" points="1">R</Field>
        <Field id="F29" row="2" col="9" usability="1" points="1">X</Field>
        <Field id="F30" row="3" col="0" usability="1" points="1">E</Field>
        <Field id="F31" row="3" col="1" usability="1" points="1">I</Field>
        <Field id="F32" row="3" col="2" usability="1" points="1">I</Field>
        <Field id="F33" row="3" col="3" usability="1" points="1">N</Field>
        <Field id="F34" row="3" col="4" usability="1" points="1">N</Field>
        <Field id="F35" row="3" col="5" usability="1" points="1">F</Field>
        <Field id="F36" row="3" col="6" usability="1" points="1">E</Field>
        <Field id="F37" row="3" col="7" usability="1" points="1">S</Field>
        <Field id="F38" row="3" col="8" usability="1" points="1">M</Field>
        <Field id="F39" row="3" col="9" usability="1" points="1">Q</Field>
        <Field id="F40" row="4" col="0" usability="1" points="1">G</Field>
        <Field id="F41" row="4" col="1" usability="1" points="1">D</Field>
        <Field id="F42" row="4" col="2" usability="1" points="1">D</Field>
        <Field id="F43" row="4" col="3" usability="1" points="1">E</Field>
        <Field id="F44" row="4" col="4" usability="1" points="1">S</Field>
        <Field id="F45" row="4" col="5" usability="1" points="1">E</Field>
        <Field id="F46" row="4" col="6" usability="1" points="1">R</Field>
        <Field id="F47" row="4" col="7" usability="1" points="1">E</Field>
        <Field id="F48" row="4" col="8" usability="1" points="1">E</Field>
        <Field id="F49" row="4" col="9" usability="1" points="1">B</Field>
    </Jungle>
    <SnakeTypes>
        <SnakeType id="A0" points="1" amount="1">
            <Word>DIE</Word>
            <NeighborhoodStructure type="Distance">
                <Parameter value="1" />
            </NeighborhoodStructure>
        </SnakeType>
        <SnakeType id="A1" points="1" amount="1">
            <Word>DIES</Word>
            <NeighborhoodStructure type="Distance">
                <Parameter value="1" />
            </NeighborhoodStructure>
        </SnakeType>
        <SnakeType id="A2" points="1" amount="1">
            <Word>DIESE</Word>
            <NeighborhoodStructure type="Distance">
                <Parameter value="1" />
            </NeighborhoodStructure>
        </SnakeType>
        <SnakeType id="A3" points="1" amount="1">
            <Word>DIESES</Word>
            <NeighborhoodStructure type="Distance">
                <Parameter value="1" />
            </NeighborhoodStructure>
        </SnakeType>
        <SnakeType id="A4" points="1" amount="1">
            <Word>DIESEN</Word>
            <NeighborhoodStructure type="Distance">
                <Parameter value="1" />
            </NeighborhoodStructure>
        </SnakeType>
        <SnakeType id="A5" points="1" amount="1">
            <Word>DIESER</Word>
            <NeighborhoodStructure type="Distance">
                <Parameter value="1" />
            </NeighborhoodStructure>
        </SnakeType>
    </SnakeTypes>
</SnakeHunt>

=== nemouu/wordsnake-hunt/res/sh_p12_solution.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE SnakeHunt SYSTEM "snakehunt.dtd">
<SnakeHunt>
    <Time unit="s">
        <Limit>10.0</Limit>
        <Elapsed>2.7816161750000004</Elapsed>
    </Time>
    <Jungle rows="5" cols="5" signs="VIP">
        <Field id="F0" row="0" col="0" usability="5" points="5">V</Field>
        <Field id="F1" row="0" col="1" usability="8" points="8">T</Field>
        <Field id="F2" row="0" col="2" usability="7" points="7">P</Field>
        <Field id="F3" row="0" col="3" usability="3" points="3">E</Field>
        <Field id="F4" row="0" col="4" usability="4" points="4">V</Field>
        <Field id="F5" row="1" col="0" usability="4" points="4">T</Field>
        <Field id="F6" row="1" col="1" usability="4" points="4">I</Field>
        <Field id="F7" row="1" col="2" usability="6" points="6">E</Field>
        <Field id="F8" row="1" col="3" usability="8" points="8">R</Field>
        <Field id="F9" row="1" col="4" usability="8" points="8">I</Field>
        <Field id="F10" row="2" col="0" usability="9" points="9">I</Field>
        <Field id="F11" row="2" col="1" usability="3" points="3">O</Field>
        <Field id="F12" row="2" col="2" usability="7" points="7">V</Field>
        <Field id="F13" row="2" col="3" usability="3" points="3">R</Field>
        <Field id="F14" row="2" col="4" usability="2" points="2">P</Field>
        <Field id="F15" row="3" col="0" usability="4" points="4">I</Field>
        <Field id="F16" row="3" col="1" usability="2" points="2">T</Field>
        <Field id="F17" row="3" col="2" usability="2" points="2">T</Field>
        <Field id="F18" row="3" col="3" usability="6" points="6">R</Field>
        <Field id="F19" row="3" col="4" usability="9" points="9">P</Field>
        <Field id="F20" row="4" col="0" usability="6" points="6">N</Field>
        <Field id="F21" row="4" col="1" usability="2" points="2">A</Field>
        <Field id="F22" row="4" col="2" usability="0" points="0">E</Field>
        <Field id="F23" row="4" col="3" usability="9" points="9">I</Field>
        <Field id="F24" row="4" col="4" usability="4" points="4">I</Field>
    </Jungle>
    <SnakeTypes>
        <SnakeType id="A0" points="100" amount="1">
            <Word>NATTER</Word>
            <NeighborhoodStructure type="Distance">
                <Parameter value="1" />
            </NeighborhoodStructure>
        </SnakeType>
        <SnakeType id="A1" points="10" amount="1">
            <Word>OTTER</Word>
            <NeighborhoodStructure type="Distance">
                <Parameter value="1" />
            </NeighborhoodStructure>
        </SnakeType>
        <SnakeType id="A2" points="1" amount="1">
            <Word>VIPER</Word>
            <NeighborhoodStructure type="Distance">
                <Parameter value="1" />
            </NeighborhoodStructure>
        </SnakeType>
    </SnakeTypes>
    <Snakes>
        <Snake type="A2">
            <SnakeElement field="F12" />
            <SnakeElement field="F6" />
            <SnakeElement field="F2" />
            <SnakeElement field="F7" />
            <SnakeElement field="F8" />
        </Snake>
        <Snake type="A2">
            <SnakeElement field="F12" />
            <SnakeElement field="F6" />
            <SnakeElement field="F2" />
            <SnakeElement field="F7" />
            <SnakeElement field="F8" />
        </Snake>
        <Snake type="A2">
            <SnakeElement field="F12" />
            <SnakeElement field="F6" />
            <SnakeElement field="F2" />
            <SnakeElement field="F7" />
            <SnakeElement field="F8" />
        </Snake>
        <Snake type="A2">
            <SnakeElement field="F12" />
            <SnakeElement field="F6" />
            <SnakeElement field="F2" />
            <SnakeElement field="F3" />
            <SnakeElement field="F8" />
        </Snake>
        <Snake type="A1">
            <SnakeElement field="F11" />
            <SnakeElement field="F5" />
            <SnakeElement field="F1" />
            <SnakeElement field="F7" />
            <SnakeElement field="F8" />
        </Snake>
        <Snake type="A1">
            <SnakeElement field="F11" />
            <SnakeElement field="F5" />
            <SnakeElement field="F1" />
            <SnakeElement field="F7" />
            <SnakeElement field="F8" />
        </Snake>
        <Snake type="A1">
            <SnakeElement field="F11" />
            <SnakeElement field="F5" />
            <SnakeElement field="F1" />
            <SnakeElement field="F7" />
            <SnakeElement field="F8" />
        </Snake>
    </Snakes>
</SnakeHunt>

=== nemouu/wordsnake-hunt/res/sh_p5_incomplete.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE SnakeHunt SYSTEM "snakehunt.dtd" >
<SnakeHunt>
	<Time unit="s">
		<Limit>10.0</Limit>
	</Time>
	<Jungle rows="20" cols="20" signs="ABCDEFGHIJKLMNOPQRSTUVWXYZ">
	</Jungle>
	<SnakeTypes>
		<SnakeType id="A0" points="1" amount="3">
			<Word>FERNUNI</Word>
			<NeighborhoodStructure type="Distance">
				<Parameter value="1" />
			</NeighborhoodStructure>
		</SnakeType>
		<SnakeType id="A1" points="1" amount="3">
			<Word>HAGEN</Word>
			<NeighborhoodStructure type="Jump">
				<Parameter value="2" />
				<Parameter value="1" />
			</NeighborhoodStructure>
		</SnakeType>
		<SnakeType id="A2" points="1" amount="3">
			<Word>ANACONDA</Word>
			<NeighborhoodStructure type="Jump">
				<Parameter value="3" />
				<Parameter value="2" />
			</NeighborhoodStructure>
		</SnakeType>
	</SnakeTypes>
</SnakeHunt>

=== nemouu/wordsnake-hunt/res/sh_p12_incomplete.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE SnakeHunt SYSTEM "snakehunt.dtd" >
<SnakeHunt>
	<Time unit="s">
		<Limit>10.0</Limit>
	</Time>
	<Jungle rows="5" cols="5" signs="VIP">
	</Jungle>
    <SnakeTypes>
        <SnakeType id="A0" points="100" amount="1">
            <Word>NATTER</Word>
            <NeighborhoodStructure type="Distance">
                <Parameter value="1" />
            </NeighborhoodStructure>
        </SnakeType>
        <SnakeType id="A1" points="10" amount="1">
            <Word>OTTER</Word>
            <NeighborhoodStructure type="Distance">
                <Parameter value="1" />
            </NeighborhoodStructure>
        </SnakeType>
        <SnakeType id="A2" points="1" amount="1">
            <Word>VIPER</Word>
            <NeighborhoodStructure type="Distance">
                <Parameter value="1" />
            </NeighborhoodStructure>
        </SnakeType>
    </SnakeTypes>
</SnakeHunt>

=== nemouu/wordsnake-hunt/res/sh_p7_solution.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE SnakeHunt SYSTEM "snakehunt.dtd">
<SnakeHunt>
    <Time unit="s">
        <Limit>10.0</Limit>
        <Elapsed>10.000004491</Elapsed>
    </Time>
    <Jungle rows="10" cols="5" signs="!&quot;§$%&amp;/()=?+*~#',;:-_@€&lt;&gt;|">
        <Field id="F0" row="0" col="0" usability="1" points="5">N</Field>
        <Field id="F1" row="0" col="1" usability="1" points="8">a</Field>
        <Field id="F2" row="0" col="2" usability="1" points="7">e</Field>
        <Field id="F3" row="0" col="3" usability="1" points="3">h</Field>
        <Field id="F4" row="0" col="4" usability="1" points="4">;</Field>
        <Field id="F5" row="1" col="0" usability="1" points="4">N</Field>
        <Field id="F6" row="1" col="1" usability="1" points="4">H</Field>
        <Field id="F7" row="1" col="2" usability="1" points="6">G</Field>
        <Field id="F8" row="1" col="3" usability="1" points="8">g</Field>
        <Field id="F9" row="1" col="4" usability="1" points="8">E</Field>
        <Field id="F10" row="2" col="0" usability="1" points="9">E</Field>
        <Field id="F11" row="2" col="1" usability="1" points="3">A</Field>
        <Field id="F12" row="2" col="2" usability="1" points="7">N</Field>
        <Field id="F13" row="2" col="3" usability="1" points="3">G</Field>
        <Field id="F14" row="2" col="4" usability="1" points="2">e</Field>
        <Field id="F15" row="3" col="0" usability="1" points="4">N</Field>
        <Field id="F16" row="3" col="1" usability="1" points="2">n</Field>
        <Field id="F17" row="3" col="2" usability="1" points="2">A</Field>
        <Field id="F18" row="3" col="3" usability="1" points="6">A</Field>
        <Field id="F19" row="3" col="4" usability="1" points="9">h</Field>
        <Field id="F20" row="4" col="0" usability="1" points="6">G</Field>
        <Field id="F21" row="4" col="1" usability="1" points="2">e</Field>
        <Field id="F22" row="4" col="2" usability="1" points="0">e</Field>
        <Field id="F23" row="4" col="3" usability="1" points="9">G</Field>
        <Field id="F24" row="4" col="4" usability="1" points="4">!</Field>
        <Field id="F25" row="5" col="0" usability="1" points="9">N</Field>
        <Field id="F26" row="5" col="1" usability="1" points="8">G</Field>
        <Field id="F27" row="5" col="2" usability="1" points="3">g</Field>
        <Field id="F28" row="5" col="3" usability="1" points="7">H</Field>
        <Field id="F29" row="5" col="4" usability="1" points="2">H</Field>
        <Field id="F30" row="6" col="0" usability="1" points="5">(</Field>
        <Field id="F31" row="6" col="1" usability="1" points="4">e</Field>
        <Field id="F32" row="6" col="2" usability="1" points="0">=</Field>
        <Field id="F33" row="6" col="3" usability="1" points="6">n</Field>
        <Field id="F34" row="6" col="4" usability="1" points="3">e</Field>
        <Field id="F35" row="7" col="0" usability="1" points="5">a</Field>
        <Field id="F36" row="7" col="1" usability="1" points="9">h</Field>
        <Field id="F37" row="7" col="2" usability="1" points="0">N</Field>
        <Field id="F38" row="7" col="3" usability="1" points="5">*</Field>
        <Field id="F39" row="7" col="4" usability="1" points="4">a</Field>
        <Field id="F40" row="8" col="0" usability="1" points="5">&gt;</Field>
        <Field id="F41" row="8" col="1" usability="1" points="0">H</Field>
        <Field id="F42" row="8" col="2" usability="1" points="7">G</Field>
        <Field id="F43" row="8" col="3" usability="1" points="7">A</Field>
        <Field id="F44" row="8" col="4" usability="1" points="7">a</Field>
        <Field id="F45" row="9" col="0" usability="1" points="2">_</Field>
        <Field id="F46" row="9" col="1" usability="1" points="0">€</Field>
        <Field id="F47" row="9" col="2" usability="1" points="8">€</Field>
        <Field id="F48" row="9" col="3" usability="1" points="0">?</Field>
        <Field id="F49" row="9" col="4" usability="1" points="7">h</Field>
    </Jungle>
    <SnakeTypes>
        <SnakeType id="A0" points="1" amount="2">
            <Word>hagen</Word>
            <NeighborhoodStructure type="Distance">
                <Parameter value="3" />
            </NeighborhoodStructure>
        </SnakeType>
        <SnakeType id="A1" points="1" amount="2">
            <Word>HAGEN</Word>
            <NeighborhoodStructure type="Distance">
                <Parameter value="3" />
            </NeighborhoodStructure>
        </SnakeType>
        <SnakeType id="A2" points="1" amount="2">
            <Word>HaGeN</Word>
            <NeighborhoodStructure type="Distance">
                <Parameter value="3" />
            </NeighborhoodStructure>
        </SnakeType>
        <SnakeType id="A3" points="1" amount="2">
            <Word>hAGeN</Word>
            <NeighborhoodStructure type="Distance">
                <Parameter value="3" />
            </NeighborhoodStructure>
        </SnakeType>
    </SnakeTypes>
    <Snakes>
        <Snake type="A0">
            <SnakeElement field="F19" />
            <SnakeElement field="F1" />
            <SnakeElement field="F8" />
            <SnakeElement field="F2" />
            <SnakeElement field="F16" />
        </Snake>
        <Snake type="A0">
            <SnakeElement field="F36" />
            <SnakeElement field="F44" />
            <SnakeElement field="F27" />
            <SnakeElement field="F31" />
            <SnakeElement field="F33" />
        </Snake>
        <Snake type="A1">
            <SnakeElement field="F28" />
            <SnakeElement field="F18" />
            <SnakeElement field="F23" />
            <SnakeElement field="F10" />
            <SnakeElement field="F0" />
        </Snake>
        <Snake type="A3">
            <SnakeElement field="F49" />
            <SnakeElement field="F43" />
            <SnakeElement field="F26" />
            <SnakeElement field="F21" />
            <SnakeElement field="F25" />
        </Snake>
        <Snake type="A1">
            <SnakeElement field="F6" />
            <SnakeElement field="F11" />
            <SnakeElement field="F7" />
            <SnakeElement field="F9" />
            <SnakeElement field="F12" />
        </Snake>
        <Snake type="A3">
            <SnakeElement field="F3" />
            <SnakeElement field="F17" />
            <SnakeElement field="F20" />
            <SnakeElement field="F22" />
            <SnakeElement field="F5" />
        </Snake>
        <Snake type="A2">
            <SnakeElement field="F29" />
            <SnakeElement field="F39" />
            <SnakeElement field="F42" />
            <SnakeElement field="F34" />
            <SnakeElement field="F37" />
        </Snake>
    </Snakes>
</SnakeHunt>

=== nemouu/wordsnake-hunt/res/sh_p9_incomplete.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE SnakeHunt SYSTEM "snakehunt.dtd" >
<SnakeHunt>
	<Time unit="h">
		<Limit>0.005</Limit>
	</Time>
	<Jungle rows="8" cols="10" signs="ÁÀĂÂÄÓÒǑÔÖ">
	</Jungle>
	<SnakeTypes>
		<SnakeType id="A0" points="10" amount="3">
			<Word>ANNA</Word>
			<NeighborhoodStructure type="Distance">
				<Parameter value="1" />
			</NeighborhoodStructure>
		</SnakeType>
		<SnakeType id="A1" points="1" amount="3">
			<Word>ANNA</Word>
			<NeighborhoodStructure type="Distance">
				<Parameter value="2" />
			</NeighborhoodStructure>
		</SnakeType>
		<SnakeType id="A2" points="10" amount="3">
			<Word>OTTO</Word>
			<NeighborhoodStructure type="Distance">
				<Parameter value="1" />
			</NeighborhoodStructure>
		</SnakeType>
		<SnakeType id="A3" points="1" amount="3">
			<Word>OTTO</Word>
			<NeighborhoodStructure type="Distance">
				<Parameter value="2" />
			</NeighborhoodStructure>
		</SnakeType>
		<SnakeType id="A4" points="30" amount="1">
			<Word>ANON</Word>
			<NeighborhoodStructure type="Jump">
				<Parameter value="2" />
				<Parameter value="1" />
			</NeighborhoodStructure>
		</SnakeType>
		<SnakeType id="A5" points="20" amount="1">
			<Word>NONA</Word>
			<NeighborhoodStructure type="Jump">
				<Parameter value="2" />
				<Parameter value="1" />
			</NeighborhoodStructure>
		</SnakeType>
	</SnakeTypes>
</SnakeHunt>

=== nemouu/wordsnake-hunt/res/sh_afternoon_incomplete.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE SnakeHunt SYSTEM "snakehunt.dtd" >
<SnakeHunt>
	<Time unit="s">
		<Limit>10.0</Limit>
	</Time>
	<Jungle rows="15" cols="20" signs=".">
	</Jungle>
	<SnakeTypes>
		<SnakeType id="A0" points="1" amount="1">
			<Word>FERNUNI</Word>
			<NeighborhoodStructure type="Star">
				<Parameter value="2" />
				<Parameter value="2" />
			</NeighborhoodStructure>
		</SnakeType>
		<SnakeType id="A1" points="1" amount="1">
			<Word>HAGEN</Word>
			<NeighborhoodStructure type="Star">
				<Parameter value="3" />
				<Parameter value="0" />
			</NeighborhoodStructure>
		</SnakeType>
		<SnakeType id="A2" points="1" amount="1">
			<Word>PROPRA</Word>
			<NeighborhoodStructure type="Star">
				<Parameter value="0" />
				<Parameter value="4" />
			</NeighborhoodStructure>
		</SnakeType>
	</SnakeTypes>
</SnakeHunt>
