=== nemouu/wordsnake-hunt/res/snakehunt.dtd
<!ELEMENT SnakeHunt (Time?, Jungle, SnakeTypes, 
        Snakes?)>
<!ELEMENT Time (Limit, Elapsed?)> 
<!ATTLIST Time
    unit (ms|s|min|h|d) "s"
>
<!ELEMENT Limit (#PCDATA)>
<!ELEMENT Elapsed (#PCDATA)>
<!ELEMENT Jungle (Field*)>
<!ATTLIST Jungle
    rows CDATA #REQUIRED
    cols CDATA #REQUIRED
    signs CDATA #REQUIRED
>
<!ELEMENT Field (#PCDATA)> 
<!ATTLIST Field
    id ID #REQUIRED
    row CDATA #REQUIRED
    col CDATA #REQUIRED
    usability CDATA "1"
    points CDATA "1"
>
<!ELEMENT SnakeTypes (SnakeType+)>
<!ELEMENT SnakeType (Word, NeighborhoodStructure)>
<!ATTLIST SnakeType
    id ID #REQUIRED
    points CDATA "1"
    amount CDATA #REQUIRED
>
<!ELEMENT Word (#PCDATA)>
<!ELEMENT NeighborhoodStructure (Parameter*)>
<!ATTLIST NeighborhoodStructure
    type CDATA #REQUIRED
>
<!ELEMENT Parameter EMPTY>
<!ATTLIST Parameter
    value CDATA #REQUIRED
>
<!ELEMENT Snakes (Snake*)>
<!ELEMENT Snake (SnakeElement+)>
<!ATTLIST Snake
    type IDREF #REQUIRED
>
<!ELEMENT SnakeElement EMPTY>
<!ATTLIST SnakeElement
    field IDREF #REQUIRED
>

=== nemouu/wordsnake-hunt/res/sh_p10_incomplete.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE SnakeHunt SYSTEM "snakehunt.dtd" >
<SnakeHunt>
	<Time unit="d">
		<Limit>0.0002</Limit>
	</Time>
	<Jungle rows="6" cols="6" signs="BELN">
	</Jungle>
	<SnakeTypes>
		<SnakeType id="A0" points="20" amount="2">
			<Word>LEBEN</Word>
			<NeighborhoodStructure type="Distance">
				<Parameter value="2" />
			</NeighborhoodStructure>
		</SnakeType>
		<SnakeType id="A1" points="1" amount="2">
			<Word>NEBEL</Word>
			<NeighborhoodStructure type="Distance">
				<Parameter value="3" />
			</NeighborhoodStructure>
		</SnakeType>
	</SnakeTypes>
</SnakeHunt>

=== nemouu/wordsnake-hunt/res/sh_p3_problem_instance.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE SnakeHunt SYSTEM "snakehunt.dtd">
<SnakeHunt>
    <Time unit="s">
        <Limit>10.0</Limit>
    </Time>
    <Jungle rows="11" cols="11" signs="ABCDEFGHIJKLMNOPQRSTUVWXYZ">
        <Field id="F0" row="0" col="0" usability="1" points="1">K</Field>
        <Field id="F1" row="0" col="1" usability="1" points="1">E</Field>
        <Field id="F2" row="0" col="2" usability="1" points="1">L</Field>
        <Field id="F3" row="0" col="3" usability="1" points="1">R</Field>
        <Field id="F4" row="0" col="4" usability="1" points="1">A</Field>
        <Field id="F5" row="0" col="5" usability="1" points="1">H</Field>
        <Field id="F6" row="0" col="6" usability="1" points="1">J</Field>
        <Field id="F7" row="0" col="7" usability="1" points="1">M</Field>
        <Field id="F8" row="0" col="8" usability="1" points="1">Y</Field>
        <Field id="F9" row="0" col="9" usability="1" points="1">U</Field>
        <Field id="F10" row="0" col="10" usability="1" points="1">S</Field>
        <Field id="F11" row="1" col="0" usability="1" points="1">T</Field>
        <Field id="F12" row="1" col="1" usability="1" points="1">E</Field>
        <Field id="F13" row="1" col="2" usability="1" points="1">T</Field>
        <Field id="F14" row="1" col="3" usability="1" points="1">W</Field>
        <Field id="F15" row="1" col="4" usability="1" points="1">W</Field>
        <Field id="F16" row="1" col="5" usability="1" points="1">T</Field>
        <Field id="F17" row="1" col="6" usability="1" points="1">A</Field>
        <Field id="F18" row="1" col="7" usability="1" points="1">H</Field>
        <Field id="F19" row="1" col="8" usability="1" points="1">S</Field>
        <Field id="F20" row="1" col="9" usability="1" points="1">E</Field>
        <Field id="F21" row="1" col="10" usability="1" points="1">E</Field>
        <Field id="F22" row="2" col="0" usability="1" points="1">K</Field>
        <Field id="F23" row="2" col="1" usability="1" points="1">R</Field>
        <Field id="F24" row="2" col="2" usability="1" points="1">S</Field>
        <Field id="F25" row="2" col="3" usability="1" points="1">R</Field>
        <Field id="F26" row="2" col="4" usability="1" points="1">R</Field>
        <Field id="F27" row="2" col="5" usability="1" points="1">F</Field>
        <Field id="F28" row="2" col="6" usability="1" points="1">I</Field>
        <Field id="F29" row="2" col="7" usability="1" points="1">C</Field>
        <Field id="F30" row="2" col="8" usability="1" points="1">L</Field>
        <Field id="F31" row="2" col="9" usability="1" points="1">L</Field>
        <Field id="F32" row="2" col="10" usability="1" points="1">G</Field>
        <Field id="F33" row="3" col="0" usability="1" points="1">X</Field>
        <Field id="F34" row="3" col="1" usability="1" points="1">I</Field>
        <Field id="F35" row="3" col="2" usability="1" points="1">Z</Field>
        <Field id="F36" row="3" col="3" usability="1" points="1">D</Field>
        <Field id="F37" row="3" col="4" usability="1" points="1">H</Field>
        <Field id="F38" row="3" col="5" usability="1" points="1">F</Field>
        <Field id="F39" row="3" col="6" usability="1" points="1">F</Field>
        <Field id="F40" row="3" col="7" usability="1" points="1">H</Field>
        <Field id="F41" row="3" col="8" usability="1" points="1">C</Field>
        <Field id="F42" row="3" col="9" usability="1" points="1">N</Field>
        <Field id="F43" row="3" col="10" usability="1" points="1">T</Field>
        <Field id="F44" row="4" col="0" usability="1" points="1">N</Field>
        <Field id="F45" row="4" col="1" usability="1" points="1">F</Field>
        <Field id="F46" row="4" col="2" usability="1" points="1">I</Field>
        <Field id="F47" row="4" col="3" usability="1" points="1">O</Field>
        <Field id="F48" row="4" col="4" usability="1" points="1">A</Field>
        <Field id="F49" row="4" col="5" usability="1" points="1">M</Field>
        <Field id="F50" row="4" col="6" usability="1" points="1">F</Field>
        <Field id="F51" row="4" col="7" usability="1" points="1">S</Field>
        <Field id="F52" row="4" col="8" usability="1" points="1">Q</Field>
        <Field id="F53" row="4" col="9" usability="1" points="1">M</Field>
        <Field id="F54" row="4" col="10" usability="1" points="1">E</Field>
        <Field id="F55" row="5" col="0" usability="1" points="1">G</Field>
        <Field id="F56" row="5" col="1" usability="1" points="1">E</Field>
        <Field id="F57" row="5" col="2" usability="1" points="1">T</Field>
        <Field id="F58" row="5" col="3" usability="1" points="1">E</Field>
        <Field id="F59" row="5" col="4" usability="1" points="1">N</Field>
        <Field id="F60" row="5" col="5" usability="1" points="1">E</Field>
        <Field id="F61" row="5" col="6" usability="1" points="1">P</Field>
        <Field id="F62" row="5" col="7" usability="1" points="1">F</Field>
        <Field id="F63" row="5" col="8" usability="1" points="1">B</Field>
        <Field id="F64" row="5" col="9" usability="1" points="1">E</Field>
        <Field id="F65" row="5" col="10" usability="1" points="1">A</Field>
        <Field id="F66" row="6" col="0" usability="1" points="1">T</Field>
        <Field id="F67" row="6" col="1" usability="1" points="1">Ä</Field>
        <Field id="F68" row="6" col="2" usability="1" points="1">N</Field>
        <Field id="F69" row="6" col="3" usability="1" points="1">A</Field>
        <Field id="F70" row="6" col="4" usability="1" points="1">D</Field>
        <Field id="F71" row="6" col="5" usability="1" points="1">A</Field>
        <Field id="F72" row="6" col="6" usability="1" points="1">M</Field>
        <Field id="F73" row="6" col="7" usability="1" points="1">O</Field>
        <Field id="F74" row="6" col="8" usability="1" points="1">A</Field>
        <Field id="F75" row="6" col="9" usability="1" points="1">T</Field>
        <Field id="F76" row="6" col="10" usability="1" points="1">E</Field>
        <Field id="F77" row="7" col="0" usability="1" points="1">P</Field>
        <Field id="F78" row="7" col="1" usability="1" points="1">E</Field>
        <Field id="F79" row="7" col="2" usability="1" points="1">Z</Field>
        <Field id="F80" row="7" col="3" usability="1" points="1">H</Field>
        <Field id="F81" row="7" col="4" usability="1" points="1">U</Field>
        <Field id="F82" row="7" col="5" usability="1" points="1">I</Field>
        <Field id="F83" row="7" col="6" usability="1" points="1">E</Field>
        <Field id="F84" row="7" col="7" usability="1" points="1">S</Field>
        <Field id="F85" row="7" col="8" usability="1" points="1">E</Field>
        <Field id="F86" row="7" col="9" usability="1" points="1">B</Field>
        <Field id="F87" row="7" col="10" usability="1" points="1">N</Field>
        <Field id="F88" row="8" col="0" usability="1" points="1">D</Field>
        <Field id="F89" row="8" col="1" usability="1" points="1">Z</Field>
        <Field id="F90" row="8" col="2" usability="1" points="1">S</Field>
        <Field id="F91" row="8" col="3" usability="1" points="1">A</Field>
        <Field id="F92" row="8" col="4" usability="1" points="1">R</Field>
        <Field id="F93" row="8" col="5" usability="1" points="1">B</Field>
        <Field id="F94" row="8" col="6" usability="1" points="1">P</Field>
        <Field id="F95" row="8" col="7" usability="1" points="1">M</Field>
        <Field id="F96" row="8" col="8" usability="1" points="1">R</Field>
        <Field id="F97" row="8" col="9" usability="1" points="1">U</Field>
        <Field id="F98" row="8" col="10" usability="1" points="1">U</Field>
        <Field id="F99" row="9" col="0" usability="1" points="1">Q</Field>
        <Field id="F100" row="9" col="1" usability="1" points="1">C</Field>
        <Field id="F101" row="9" col="2" usability="1" points="1">U</Field>
        <Field id="F102" row="9" col="3" usability="1" points="1">X</Field>
        <Field id="F103" row="9" col="4" usability="1" points="1">J</Field>
        <Field id="F104" row="9" col="5" usability="1" points="1">T</Field>
        <Field id="F105" row="9" col="6" usability="1" points="1">S</Field>
        <Field id="F106" row="9" col="7" usability="1" points="1">E</Field>
        <Field id="F107" row="9" col="8" usability="1" points="1">K</Field>
        <Field id="F108" row="9" col="9" usability="1" points="1">T</Field>
        <Field id="F109" row="9" col="10" usability="1" points="1">A</Field>
        <Field id="F110" row="10" col="0" usability="1" points="1">G</Field>
        <Field id="F111" row="10" col="1" usability="1" points="1">D</Field>
        <Field id="F112" row="10" col="2" usability="1" points="1">Y</Field>
        <Field id="F113" row="10" col="3" usability="1" points="1">P</Field>
        <Field id="F114" row="10" col="4" usability="1" points="1">T</Field>
        <Field id="F115" row="10" col="5" usability="1" points="1">B</Field>
        <Field id="F116" row="10" col="6" usability="1" points="1">E</Field>
        <Field id="F117" row="10" col="7" usability="1" points="1">W</Field>
        <Field id="F118" row="10" col="8" usability="1" points="1">R</Field>
        <Field id="F119" row="10" col="9" usability="1" points="1">B</Field>
        <Field id="F120" row="10" col="10" usability="1" points="1">X</Field>
    </Jungle>
    <SnakeTypes>
        <SnakeType id="A0" points="1" amount="1">
            <Word>DONAUDAMPFSCHIFFFAHRTSELEKTRIZITÄTENHAUPTBETRIEBSWERKBAUUNTERBEAMTENGESELLSCHAFT</Word>
            <NeighborhoodStructure type="Distance">
                <Parameter value="1" />
            </NeighborhoodStructure>
        </SnakeType>
    </SnakeTypes>
</SnakeHunt>

=== nemouu/wordsnake-hunt/res/sh_p11_incomplete.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE SnakeHunt SYSTEM "snakehunt.dtd" >
<SnakeHunt>
	<Time unit="s">
		<Limit>10.0</Limit>
	</Time>
	<Jungle rows="7" cols="7" signs="AEIOU">
	</Jungle>
    <SnakeTypes>
        <SnakeType id="A0" points="10" amount="1">
            <Word>ADA</Word>
            <NeighborhoodStructure type="Distance">
                <Parameter value="1" />
            </NeighborhoodStructure>
        </SnakeType>
        <SnakeType id="A1" points="10" amount="1">
            <Word>AMY</Word>
            <NeighborhoodStructure type="Distance">
                <Parameter value="1" />
            </NeighborhoodStructure>
        </SnakeType>
        <SnakeType id="A2" points="10" amount="1">
            <Word>ANN</Word>
            <NeighborhoodStructure type="Distance">
                <Parameter value="1" />
            </NeighborhoodStructure>
        </SnakeType>
        <SnakeType id="A3" points="10" amount="1">
            <Word>AVA</Word>
            <NeighborhoodStructure type="Distance">
                <Parameter value="1" />
            </NeighborhoodStructure>
        </SnakeType>
        <SnakeType id="A4" points="10" amount="1">
            <Word>BEA</Word>
            <NeighborhoodStructure type="Distance">
                <Parameter value="1" />
            </NeighborhoodStructure>
        </SnakeType>
        <SnakeType id="A5" points="10" amount="1">
            <Word>ELA</Word>
            <NeighborhoodStructure type="Distance">
                <Parameter value="1" />
            </NeighborhoodStructure>
        </SnakeType>
        <SnakeType id="A6" points="10" amount="1">
            <Word>EVA</Word>
            <NeighborhoodStructure type="Distance">
                <Parameter value="1" />
            </NeighborhoodStructure>
        </SnakeType>
        <SnakeType id="A7" points="10" amount="1">
            <Word>IDA</Word>
            <NeighborhoodStructure type="Distance">
                <Parameter value="1" />
            </NeighborhoodStructure>
        </SnakeType>
        <SnakeType id="A8" points="10" amount="1">
            <Word>INA</Word>
            <NeighborhoodStructure type="Distance">
                <Parameter value="1" />
            </NeighborhoodStructure>
        </SnakeType>
        <SnakeType id="A9" points="10" amount="1">
            <Word>ISA</Word>
            <NeighborhoodStructure type="Distance">
                <Parameter value="1" />
            </NeighborhoodStructure>
        </SnakeType>
        <SnakeType id="A10" points="10" amount="1">
            <Word>LEA</Word>
            <NeighborhoodStructure type="Distance">
                <Parameter value="1" />
            </NeighborhoodStructure>
        </SnakeType>
        <SnakeType id="A11" points="10" amount="1">
            <Word>LIA</Word>
            <NeighborhoodStructure type="Distance">
                <Parameter value="1" />
            </NeighborhoodStructure>
        </SnakeType>
        <SnakeType id="A12" points="10" amount="1">
            <Word>LIN</Word>
            <NeighborhoodStructure type="Distance">
                <Parameter value="1" />
            </NeighborhoodStructure>
        </SnakeType>
        <SnakeType id="A13" points="10" amount="1">
            <Word>LIV</Word>
            <NeighborhoodStructure type="Distance">
                <Parameter value="1" />
            </NeighborhoodStructure>
        </SnakeType>
        <SnakeType id="A14" points="10" amount="1">
            <Word>MIA</Word>
            <NeighborhoodStructure type="Distance">
                <Parameter value="1" />
            </NeighborhoodStructure>
        </SnakeType>
        <SnakeType id="A15" points="10" amount="1">
            <Word>PIA</Word>
            <NeighborhoodStructure type="Distance">
                <Parameter value="1" />
            </NeighborhoodStructure>
        </SnakeType>
        <SnakeType id="A16" points="10" amount="1">
            <Word>RIA</Word>
            <NeighborhoodStructure type="Distance">
                <Parameter value="1" />
            </NeighborhoodStructure>
        </SnakeType>
        <SnakeType id="A17" points="10" amount="1">
            <Word>SUE</Word>
            <NeighborhoodStructure type="Distance">
                <Parameter value="1" />
            </NeighborhoodStructure>
        </SnakeType>
        <SnakeType id="A18" points="10" amount="1">
            <Word>UTE</Word>
            <NeighborhoodStructure type="Distance">
                <Parameter value="1" />
            </NeighborhoodStructure>
        </SnakeType>
        <SnakeType id="A19" points="10" amount="1">
            <Word>ZOE</Word>
            <NeighborhoodStructure type="Distance">
                <Parameter value="1" />
            </NeighborhoodStructure>
        </SnakeType>
    </SnakeTypes>
</SnakeHunt>

=== nemouu/wordsnake-hunt/res/sh_p1_my_solution.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE SnakeHunt SYSTEM "snakehunt.dtd">
<SnakeHunt>
  <Time unit="s">
    <Limit>60.0</Limit>
    <Elapsed>9.01037E-4</Elapsed>
  </Time>
  <Jungle rows="2" cols="4" signs="ABCDEFGHIJKLMNOPQRSTUVWXYZ">
    <Field id="F0" row="0" col="0" usability="1" points="1">F</Field>
    <Field id="F1" row="0" col="1" usability="1" points="1">E</Field>
    <Field id="F2" row="0" col="2" usability="1" points="1">R</Field>
    <Field id="F3" row="0" col="3" usability="1" points="1">N</Field>
    <Field id="F4" row="1" col="0" usability="1" points="1">X</Field>
    <Field id="F5" row="1" col="1" usability="1" points="1">I</Field>
    <Field id="F6" row="1" col="2" usability="1" points="1">N</Field>
    <Field id="F7" row="1" col="3" usability="1" points="1">U</Field>
  </Jungle>
  <SnakeTypes>
    <SnakeType id="A0" points="1" amount="1">
      <Word>FERNUNI</Word>
      <NeighborhoodStructure type="Distance">
        <Parameter value="1" />
      </NeighborhoodStructure>
    </SnakeType>
  </SnakeTypes>
  <Snakes>
    <Snake type="A0">
      <SnakeElement field="F0" />
      <SnakeElement field="F1" />
      <SnakeElement field="F2" />
      <SnakeElement field="F3" />
      <SnakeElement field="F7" />
      <SnakeElement field="F6" />
      <SnakeElement field="F5" />
    </Snake>
  </Snakes>
</SnakeHunt>

=== nemouu/wordsnake-hunt/res/sh_p8_solution.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE SnakeHunt SYSTEM "snakehunt.dtd">
<SnakeHunt>
    <Time unit="min">
        <Limit>0.2</Limit>
        <Elapsed>0.2000001336666667</Elapsed>
    </Time>
    <Jungle rows="8" cols="8" signs="☀☁☂☃☄★☆☇☔☕☼☽☾♨♫⚘⚽⛄⛅⛆⛈⛐⛰⛵⛷⛸⛹⛺">
        <Field id="F0" row="0" col="0" usability="1" points="5">☻</Field>
        <Field id="F1" row="0" col="1" usability="1" points="8">☺</Field>
        <Field id="F2" row="0" col="2" usability="1" points="7">☻</Field>
        <Field id="F3" row="0" col="3" usability="1" points="3">⛸</Field>
        <Field id="F4" row="0" col="4" usability="1" points="4">☄</Field>
        <Field id="F5" row="0" col="5" usability="1" points="4">☺</Field>
        <Field id="F6" row="0" col="6" usability="1" points="4">☻</Field>
        <Field id="F7" row="0" col="7" usability="1" points="6">☺</Field>
        <Field id="F8" row="1" col="0" usability="1" points="8">☺</Field>
        <Field id="F9" row="1" col="1" usability="1" points="8">☻</Field>
        <Field id="F10" row="1" col="2" usability="1" points="9">☺</Field>
        <Field id="F11" row="1" col="3" usability="1" points="3">☺</Field>
        <Field id="F12" row="1" col="4" usability="1" points="7">☻</Field>
        <Field id="F13" row="1" col="5" usability="1" points="3">☻</Field>
        <Field id="F14" row="1" col="6" usability="1" points="2">⚘</Field>
        <Field id="F15" row="1" col="7" usability="1" points="4">☻</Field>
        <Field id="F16" row="2" col="0" usability="1" points="2">P</Field>
        <Field id="F17" row="2" col="1" usability="1" points="2">☺</Field>
        <Field id="F18" row="2" col="2" usability="1" points="6">P</Field>
        <Field id="F19" row="2" col="3" usability="1" points="9">R</Field>
        <Field id="F20" row="2" col="4" usability="1" points="6">☻</Field>
        <Field id="F21" row="2" col="5" usability="1" points="2">⛐</Field>
        <Field id="F22" row="2" col="6" usability="1" points="0">☺</Field>
        <Field id="F23" row="2" col="7" usability="1" points="9">☺</Field>
        <Field id="F24" row="3" col="0" usability="1" points="4">☻</Field>
        <Field id="F25" row="3" col="1" usability="1" points="9">R</Field>
        <Field id="F26" row="3" col="2" usability="1" points="8">☺</Field>
        <Field id="F27" row="3" col="3" usability="1" points="3">♡</Field>
        <Field id="F28" row="3" col="4" usability="1" points="7">☺</Field>
        <Field id="F29" row="3" col="5" usability="1" points="2">☺</Field>
        <Field id="F30" row="3" col="6" usability="1" points="5">☺</Field>
        <Field id="F31" row="3" col="7" usability="1" points="4">☻</Field>
        <Field id="F32" row="4" col="0" usability="1" points="0">☻</Field>
        <Field id="F33" row="4" col="1" usability="1" points="6">☻</Field>
        <Field id="F34" row="4" col="2" usability="1" points="3">☺</Field>
        <Field id="F35" row="4" col="3" usability="1" points="5">☻</Field>
        <Field id="F36" row="4" col="4" usability="1" points="9">P</Field>
        <Field id="F37" row="4" col="5" usability="1" points="0">☻</Field>
        <Field id="F38" row="4" col="6" usability="1" points="5">☺</Field>
        <Field id="F39" row="4" col="7" usability="1" points="4">☻</Field>
        <Field id="F40" row="5" col="0" usability="1" points="5">☺</Field>
        <Field id="F41" row="5" col="1" usability="1" points="0">☺</Field>
        <Field id="F42" row="5" col="2" usability="1" points="7">☺</Field>
        <Field id="F43" row="5" col="3" usability="1" points="7">☻</Field>
        <Field id="F44" row="5" col="4" usability="1" points="7">☆</Field>
        <Field id="F45" row="5" col="5" usability="1" points="2">R</Field>
        <Field id="F46" row="5" col="6" usability="1" points="0">☻</Field>
        <Field id="F47" row="5" col="7" usability="1" points="8">☺</Field>
        <Field id="F48" row="6" col="0" usability="1" points="0">⛈</Field>
        <Field id="F49" row="6" col="1" usability="1" points="7">☺</Field>
        <Field id="F50" row="6" col="2" usability="1" points="2">☻</Field>
        <Field id="F51" row="6" col="3" usability="1" points="3">♫</Field>
        <Field id="F52" row="6" col="4" usability="1" points="6">☺</Field>
        <Field id="F53" row="6" col="5" usability="1" points="5">P</Field>
        <Field id="F54" row="6" col="6" usability="1" points="6">☻</Field>
        <Field id="F55" row="6" col="7" usability="1" points="5">⛰</Field>
        <Field id="F56" row="7" col="0" usability="1" points="8">☻</Field>
        <Field id="F57" row="7" col="1" usability="1" points="9">☼</Field>
        <Field id="F58" row="7" col="2" usability="1" points="4">⛈</Field>
        <Field id="F59" row="7" col="3" usability="1" points="4">♥</Field>
        <Field id="F60" row="7" col="4" usability="1" points="0">R</Field>
        <Field id="F61" row="7" col="5" usability="1" points="1">☻</Field>
        <Field id="F62" row="7" col="6" usability="1" points="6">★</Field>
        <Field id="F63" row="7" col="7" usability="1" points="3">★</Field>
    </Jungle>
    <SnakeTypes>
        <SnakeType id="A0" points="10" amount="1">
            <Word>PR☻PR♥</Word>
            <NeighborhoodStructure type="Distance">
                <Parameter value="1" />
            </NeighborhoodStructure>
        </SnakeType>
        <SnakeType id="A1" points="10" amount="1">
            <Word>PR☺PR♡</Word>
            <NeighborhoodStructure type="Distance">
                <Parameter value="1" />
            </NeighborhoodStructure>
        </SnakeType>
        <SnakeType id="A2" points="1" amount="6">
            <Word>☺☻</Word>
            <NeighborhoodStructure type="Distance">
                <Parameter value="1" />
            </NeighborhoodStructure>
        </SnakeType>
        <SnakeType id="A3" points="3" amount="4">
            <Word>☺☻☺☻</Word>
            <NeighborhoodStructure type="Distance">
                <Parameter value="1" />
            </NeighborhoodStructure>
        </SnakeType>
        <SnakeType id="A4" points="6" amount="2">
            <Word>☺☻☺☻☺☻</Word>
            <NeighborhoodStructure type="Distance">
                <Parameter value="1" />
            </NeighborhoodStructure>
        </SnakeType>
    </SnakeTypes>
    <Snakes>
        <Snake type="A0">
            <SnakeElement field="F36" />
            <SnakeElement field="F45" />
            <SnakeElement field="F54" />
            <SnakeElement field="F53" />
            <SnakeElement field="F60" />
            <SnakeElement field="F59" />
        </Snake>
        <Snake type="A4">
            <SnakeElement field="F10" />
            <SnakeElement field="F9" />
            <SnakeElement field="F1" />
            <SnakeElement field="F2" />
            <SnakeElement field="F11" />
            <SnakeElement field="F12" />
        </Snake>
        <Snake type="A4">
            <SnakeElement field="F23" />
            <SnakeElement field="F15" />
            <SnakeElement field="F7" />
            <SnakeElement field="F6" />
            <SnakeElement field="F5" />
            <SnakeElement field="F13" />
        </Snake>
        <Snake type="A4">
            <SnakeElement field="F26" />
            <SnakeElement field="F33" />
            <SnakeElement field="F42" />
            <SnakeElement field="F43" />
            <SnakeElement field="F52" />
            <SnakeElement field="F61" />
        </Snake>
        <Snake type="A4">
            <SnakeElement field="F47" />
            <SnakeElement field="F39" />
            <SnakeElement field="F30" />
            <SnakeElement field="F31" />
            <SnakeElement field="F38" />
            <SnakeElement field="F46" />
        </Snake>
        <Snake type="A2">
            <SnakeElement field="F8" />
            <SnakeElement field="F0" />
        </Snake>
        <Snake type="A4">
            <SnakeElement field="F40" />
            <SnakeElement field="F32" />
            <SnakeElement field="F41" />
            <SnakeElement field="F50" />
            <SnakeElement field="F49" />
            <SnakeElement field="F56" />
        </Snake>
        <Snake type="A4">
            <SnakeElement field="F34" />
            <SnakeElement field="F35" />
            <SnakeElement field="F28" />
            <SnakeElement field="F20" />
            <SnakeElement field="F29" />
            <SnakeElement field="F37" />
        </Snake>
        <Snake type="A1">
            <SnakeElement field="F16" />
            <SnakeElement field="F25" />
            <SnakeElement field="F17" />
            <SnakeElement field="F18" />
            <SnakeElement field="F19" />
            <SnakeElement field="F27" />
        </Snake>
    </Snakes>
</SnakeHunt>

=== nemouu/wordsnake-hunt/res/sh_p3_incomplete.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE SnakeHunt SYSTEM "snakehunt.dtd" >
<SnakeHunt>
	<Time unit="s">
		<Limit>10.0</Limit>
	</Time>
	<Jungle rows="11" cols="11" signs="ABCDEFGHIJKLMNOPQRSTUVWXYZ">
	</Jungle>
	<SnakeTypes>
		<SnakeType id="A0" points="1" amount="1">
			<Word>DONAUDAMPFSCHIFFFAHRTSELEKTRIZITĂ„TENHAUPTBETRIEBSWERKBAUUNTERBEAMTENGESELLSCHAFT</Word>
			<NeighborhoodStructure type="Distance">
				<Parameter value="1" />
			</NeighborhoodStructure>
		</SnakeType>
	</SnakeTypes>
</SnakeHunt>
