=== nemouu/wordsnake-hunt/res/snakehunt.dtd
<!ELEMENT SnakeHunt (Time?, Jungle, SnakeTypes, 
        Snakes?)>
<!ELEMENT Time (Limit, Elapsed?)> 
<!ATTLIST Time
    unit (ms|s|min|h|d) "s"
>
<!ELEMENT Limit (#PCDATA)>
<!ELEMENT Elapsed (#PCDATA)>
<!ELEMENT Jungle (Field*)>
<!ATTLIST Jungle
    rows CDATA #REQUIRED
    cols CDATA #REQUIRED
    signs CDATA #REQUIRED
>
<!ELEMENT Field (#PCDATA)> 
<!ATTLIST Field
    id ID #REQUIRED
    row CDATA #REQUIRED
    col CDATA #REQUIRED
    usability CDATA "1"
    points CDATA "1"
>
<!ELEMENT SnakeTypes (SnakeType+)>
<!ELEMENT SnakeType (Word, NeighborhoodStructure)>
<!ATTLIST SnakeType
    id ID #REQUIRED
    points CDATA "1"
    amount CDATA #REQUIRED
>
<!ELEMENT Word (#PCDATA)>
<!ELEMENT NeighborhoodStructure (Parameter*)>
<!ATTLIST NeighborhoodStructure
    type CDATA #REQUIRED
>
<!ELEMENT Parameter EMPTY>
<!ATTLIST Parameter
    value CDATA #REQUIRED
>
<!ELEMENT Snakes (Snake*)>
<!ELEMENT Snake (SnakeElement+)>
<!ATTLIST Snake
    type IDREF #REQUIRED
>
<!ELEMENT SnakeElement EMPTY>
<!ATTLIST SnakeElement
    field IDREF #REQUIRED
>

=== nemouu/wordsnake-hunt/res/sh_p1_incomplete_simple_test.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE SnakeHunt SYSTEM "snakehunt.dtd">
<SnakeHunt>
  <Time unit="s">
    <Limit>60.0</Limit>
  </Time>
  <Jungle rows="2" cols="4" signs="ABCDEFGHIJKLMNOPQRSTUVWXYZ">
    <Field id="F0" row="0" col="0" usability="1" points="1">E</Field>
    <Field id="F1" row="0" col="1" usability="1" points="1">F</Field>
    <Field id="F2" row="0" col="2" usability="1" points="1">I</Field>
    <Field id="F3" row="0" col="3" usability="1" points="1">N</Field>
    <Field id="F4" row="1" col="0" usability="1" points="1">R</Field>
    <Field id="F5" row="1" col="1" usability="1" points="1">N</Field>
    <Field id="F6" row="1" col="2" usability="1" points="1">U</Field>
    <Field id="F7" row="1" col="3" usability="1" points="1">E</Field>
  </Jungle>
  <SnakeTypes>
    <SnakeType id="A0" points="1" amount="1">
      <Word>FERNUNI</Word>
      <NeighborhoodStructure type="Distance">
        <Parameter value="1" />
      </NeighborhoodStructure>
    </SnakeType>
  </SnakeTypes>
</SnakeHunt>

=== nemouu/wordsnake-hunt/res/sh_p15_incomplete.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE SnakeHunt SYSTEM "snakehunt.dtd" >
<SnakeHunt>
	<Time unit="min">
		<Limit>0.3</Limit>
	</Time>
	<Jungle rows="50" cols="50" signs="ABCDEFGHIJKLMNOPQRSTUVWXYZ">
	</Jungle>
    <SnakeTypes>
        <SnakeType id="A0" points="30" amount="50">
            <Word>ERNSTE</Word>
            <NeighborhoodStructure type="Distance">
                <Parameter value="2" />
            </NeighborhoodStructure>
        </SnakeType>
        <SnakeType id="A1" points="20" amount="50">
            <Word>ERSTEN</Word>
            <NeighborhoodStructure type="Distance">
                <Parameter value="4" />
            </NeighborhoodStructure>
        </SnakeType>
        <SnakeType id="A2" points="10" amount="50">
            <Word>NESTER</Word>
            <NeighborhoodStructure type="Distance">
                <Parameter value="6" />
            </NeighborhoodStructure>
        </SnakeType>
        <SnakeType id="A3" points="40" amount="50">
            <Word>STERNE</Word>
            <NeighborhoodStructure type="Jump">
                <Parameter value="2" />
                <Parameter value="1" />
            </NeighborhoodStructure>
        </SnakeType>
        <SnakeType id="A4" points="50" amount="50">
            <Word>RESTEN</Word>
            <NeighborhoodStructure type="Jump">
                <Parameter value="3" />
                <Parameter value="1" />
            </NeighborhoodStructure>
        </SnakeType>
        <SnakeType id="A5" points="60" amount="50">
            <Word>TRENSE</Word>
            <NeighborhoodStructure type="Jump">
                <Parameter value="3" />
                <Parameter value="2" />
            </NeighborhoodStructure>
        </SnakeType>
        <SnakeType id="A6" points="70" amount="50">
            <Word>TRESEN</Word>
            <NeighborhoodStructure type="Jump">
                <Parameter value="4" />
                <Parameter value="1" />
            </NeighborhoodStructure>
        </SnakeType>
    </SnakeTypes>
</SnakeHunt>

=== nemouu/wordsnake-hunt/res/sh_p14_problem_instance.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE SnakeHunt SYSTEM "snakehunt.dtd">
<SnakeHunt>
    <Time unit="ms">
        <Limit>100</Limit>
    </Time>
	<Jungle rows="10" cols="10" signs="EHLMNPRUV">
        <Field id="F0" row="0" col="0" usability="3" points="7">R</Field>
        <Field id="F1" row="0" col="1" usability="9" points="2">H</Field>
        <Field id="F2" row="0" col="2" usability="5" points="8">U</Field>
        <Field id="F3" row="0" col="3" usability="2" points="1">R</Field>
        <Field id="F4" row="0" col="4" usability="2" points="4">V</Field>
        <Field id="F5" row="0" col="5" usability="2" points="8">V</Field>
        <Field id="F6" row="0" col="6" usability="3" points="6">E</Field>
        <Field id="F7" row="0" col="7" usability="3" points="7">M</Field>
        <Field id="F8" row="0" col="8" usability="1" points="1">L</Field>
        <Field id="F9" row="0" col="9" usability="9" points="9">O</Field>
        <Field id="F10" row="1" col="0" usability="7" points="2">U</Field>
        <Field id="F11" row="1" col="1" usability="3" points="3">U</Field>
        <Field id="F12" row="1" col="2" usability="9" points="2">U</Field>
        <Field id="F13" row="1" col="3" usability="5" points="9">H</Field>
        <Field id="F14" row="1" col="4" usability="5" points="2">O</Field>
        <Field id="F15" row="1" col="5" usability="6" points="7">O</Field>
        <Field id="F16" row="1" col="6" usability="7" points="8">E</Field>
        <Field id="F17" row="1" col="7" usability="5" points="1">N</Field>
        <Field id="F18" row="1" col="8" usability="9" points="7">E</Field>
        <Field id="F19" row="1" col="9" usability="5" points="4">V</Field>
        <Field id="F20" row="2" col="0" usability="2" points="5">H</Field>
        <Field id="F21" row="2" col="1" usability="6" points="4">H</Field>
        <Field id="F22" row="2" col="2" usability="3" points="6">H</Field>
        <Field id="F23" row="2" col="3" usability="6" points="3">U</Field>
        <Field id="F24" row="2" col="4" usability="9" points="8">L</Field>
        <Field id="F25" row="2" col="5" usability="6" points="5">L</Field>
        <Field id="F26" row="2" col="6" usability="4" points="2">L</Field>
        <Field id="F27" row="2" col="7" usability="5" points="7">N</Field>
        <Field id="F28" row="2" col="8" usability="4" points="3">N</Field>
        <Field id="F29" row="2" col="9" usability="8" points="9">O</Field>
        <Field id="F30" row="3" col="0" usability="7" points="3">R</Field>
        <Field id="F31" row="3" col="1" usability="4" points="9">U</Field>
        <Field id="F32" row="3" col="2" usability="1" points="3">H</Field>
        <Field id="F33" row="3" col="3" usability="7" points="5">R</Field>
        <Field id="F34" row="3" col="4" usability="7" points="3">M</Field>
        <Field id="F35" row="3" col="5" usability="9" points="4">M</Field>
        <Field id="F36" row="3" col="6" usability="9" points="7">M</Field>
        <Field id="F37" row="3" col="7" usability="3" points="6">E</Field>
        <Field id="F38" row="3" col="8" usability="8" points="9">N</Field>
        <Field id="F39" row="3" col="9" usability="5" points="8">L</Field>
        <Field id="F40" row="4" col="0" usability="1" points="6">L</Field>
        <Field id="F41" row="4" col="1" usability="4" points="9">E</Field>
        <Field id="F42" row="4" col="2" usability="7" points="6">N</Field>
        <Field id="F43" row="4" col="3" usability="4" points="4">N</Field>
        <Field id="F44" row="4" col="4" usability="9" points="6">E</Field>
        <Field id="F45" row="4" col="5" usability="2" points="6">P</Field>
        <Field id="F46" row="4" col="6" usability="7" points="4">E</Field>
        <Field id="F47" row="4" col="7" usability="4" points="4">P</Field>
        <Field id="F48" row="4" col="8" usability="2" points="4">E</Field>
        <Field id="F49" row="4" col="9" usability="7" points="4">M</Field>
        <Field id="F50" row="5" col="0" usability="2" points="7">L</Field>
        <Field id="F51" row="5" col="1" usability="4" points="4">R</Field>
        <Field id="F52" row="5" col="2" usability="7" points="9">N</Field>
        <Field id="F53" row="5" col="3" usability="6" points="5">E</Field>
        <Field id="F54" row="5" col="4" usability="3" points="9">N</Field>
        <Field id="F55" row="5" col="5" usability="9" points="3">E</Field>
        <Field id="F56" row="5" col="6" usability="8" points="8">N</Field>
        <Field id="F57" row="5" col="7" usability="8" points="3">N</Field>
        <Field id="F58" row="5" col="8" usability="2" points="7">E</Field>
        <Field id="F59" row="5" col="9" usability="7" points="5">P</Field>
        <Field id="F60" row="6" col="0" usability="4" points="7">U</Field>
        <Field id="F61" row="6" col="1" usability="5" points="9">E</Field>
        <Field id="F62" row="6" col="2" usability="2" points="3">P</Field>
        <Field id="F63" row="6" col="3" usability="4" points="7">E</Field>
        <Field id="F64" row="6" col="4" usability="8" points="6">N</Field>
        <Field id="F65" row="6" col="5" usability="3" points="4">P</Field>
        <Field id="F66" row="6" col="6" usability="1" points="1">L</Field>
        <Field id="F67" row="6" col="7" usability="4" points="6">L</Field>
        <Field id="F68" row="6" col="8" usability="5" points="4">L</Field>
        <Field id="F69" row="6" col="9" usability="5" points="8">E</Field>
        <Field id="F70" row="7" col="0" usability="3" points="2">L</Field>
        <Field id="F71" row="7" col="1" usability="5" points="6">H</Field>
        <Field id="F72" row="7" col="2" usability="2" points="5">N</Field>
        <Field id="F73" row="7" col="3" usability="2" points="8">N</Field>
        <Field id="F74" row="7" col="4" usability="6" points="3">E</Field>
        <Field id="F75" row="7" col="5" usability="9" points="3">E</Field>
        <Field id="F76" row="7" col="6" usability="7" points="5">L</Field>
        <Field id="F77" row="7" col="7" usability="6" points="3">L</Field>
        <Field id="F78" row="7" col="8" usability="4" points="9">E</Field>
        <Field id="F79" row="7" col="9" usability="5" points="9">N</Field>
        <Field id="F80" row="8" col="0" usability="1" points="5">R</Field>
        <Field id="F81" row="8" col="1" usability="6" points="2">U</Field>
        <Field id="F82" row="8" col="2" usability="4" points="9">R</Field>
        <Field id="F83" row="8" col="3" usability="1" points="2">M</Field>
        <Field id="F84" row="8" col="4" usability="8" points="1">P</Field>
        <Field id="F85" row="8" col="5" usability="5" points="5">N</Field>
        <Field id="F86" row="8" col="6" usability="9" points="5">L</Field>
        <Field id="F87" row="8" col="7" usability="3" points="3">L</Field>
        <Field id="F88" row="8" col="8" usability="3" points="6">L</Field>
        <Field id="F89" row="8" col="9" usability="7" points="2">N</Field>
        <Field id="F90" row="9" col="0" usability="3" points="9">V</Field>
        <Field id="F91" row="9" col="1" usability="6" points="5">O</Field>
        <Field id="F92" row="9" col="2" usability="9" points="5">L</Field>
        <Field id="F93" row="9" col="3" usability="8" points="4">E</Field>
        <Field id="F94" row="9" col="4" usability="6" points="7">E</Field>
        <Field id="F95" row="9" col="5" usability="3" points="1">E</Field>
        <Field id="F96" row="9" col="6" usability="5" points="2">N</Field>
        <Field id="F97" row="9" col="7" usability="9" points="6">E</Field>
        <Field id="F98" row="9" col="8" usability="2" points="2">P</Field>
        <Field id="F99" row="9" col="9" usability="1" points="9">E</Field>
    </Jungle>
    <SnakeTypes>
        <SnakeType id="A0" points="115" amount="4">
            <Word>RUHR</Word>
            <NeighborhoodStructure type="Distance">
                <Parameter value="1" />
            </NeighborhoodStructure>
        </SnakeType>
        <SnakeType id="A1" points="131" amount="4">
            <Word>LENNE</Word>
            <NeighborhoodStructure type="Distance">
                <Parameter value="1" />
            </NeighborhoodStructure>
        </SnakeType>
        <SnakeType id="A2" points="213" amount="4">
            <Word>VOLME</Word>
            <NeighborhoodStructure type="Distance">
                <Parameter value="1" />
            </NeighborhoodStructure>
        </SnakeType>
        <SnakeType id="A3" points="63" amount="4">
            <Word>ENNEPE</Word>
            <NeighborhoodStructure type="Distance">
                <Parameter value="1" />
            </NeighborhoodStructure>
        </SnakeType>
    </SnakeTypes>
    <Snakes />
</SnakeHunt>

=== nemouu/wordsnake-hunt/res/sh_p11_problem_instance.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE SnakeHunt SYSTEM "snakehunt.dtd">
<SnakeHunt>
    <Time unit="s">
        <Limit>10.0</Limit>
    </Time>
    <Jungle rows="7" cols="7" signs="AEIOU">
        <Field id="F0" row="0" col="0" usability="1" points="5">I</Field>
        <Field id="F1" row="0" col="1" usability="1" points="8">M</Field>
        <Field id="F2" row="0" col="2" usability="1" points="7">U</Field>
        <Field id="F3" row="0" col="3" usability="1" points="3">B</Field>
        <Field id="F4" row="0" col="4" usability="2" points="4">L</Field>
        <Field id="F5" row="0" col="5" usability="1" points="4">I</Field>
        <Field id="F6" row="0" col="6" usability="1" points="4">A</Field>
        <Field id="F7" row="1" col="0" usability="1" points="6">A</Field>
        <Field id="F8" row="1" col="1" usability="1" points="8">V</Field>
        <Field id="F9" row="1" col="2" usability="1" points="8">T</Field>
        <Field id="F10" row="1" col="3" usability="2" points="9">E</Field>
        <Field id="F11" row="1" col="4" usability="2" points="3">I</Field>
        <Field id="F12" row="1" col="5" usability="1" points="7">P</Field>
        <Field id="F13" row="1" col="6" usability="1" points="3">I</Field>
        <Field id="F14" row="2" col="0" usability="1" points="2">I</Field>
        <Field id="F15" row="2" col="1" usability="1" points="4">A</Field>
        <Field id="F16" row="2" col="2" usability="1" points="2">V</Field>
        <Field id="F17" row="2" col="3" usability="1" points="2">E</Field>
        <Field id="F18" row="2" col="4" usability="3" points="6">A</Field>
        <Field id="F19" row="2" col="5" usability="2" points="9">N</Field>
        <Field id="F20" row="2" col="6" usability="2" points="6">N</Field>
        <Field id="F21" row="3" col="0" usability="1" points="2">L</Field>
        <Field id="F22" row="3" col="1" usability="1" points="0">E</Field>
        <Field id="F23" row="3" col="2" usability="1" points="9">U</Field>
        <Field id="F24" row="3" col="3" usability="1" points="4">I</Field>
        <Field id="F25" row="3" col="4" usability="1" points="9">R</Field>
        <Field id="F26" row="3" col="5" usability="2" points="8">A</Field>
        <Field id="F27" row="3" col="6" usability="2" points="3">A</Field>
        <Field id="F28" row="4" col="0" usability="1" points="7">Y</Field>
        <Field id="F29" row="4" col="1" usability="1" points="2">S</Field>
        <Field id="F30" row="4" col="2" usability="2" points="5">A</Field>
        <Field id="F31" row="4" col="3" usability="1" points="4">A</Field>
        <Field id="F32" row="4" col="4" usability="3" points="0">E</Field>
        <Field id="F33" row="4" col="5" usability="1" points="6">A</Field>
        <Field id="F34" row="4" col="6" usability="1" points="3">D</Field>
        <Field id="F35" row="5" col="0" usability="1" points="5">M</Field>
        <Field id="F36" row="5" col="1" usability="1" points="9">D</Field>
        <Field id="F37" row="5" col="2" usability="1" points="0">V</Field>
        <Field id="F38" row="5" col="3" usability="1" points="5">L</Field>
        <Field id="F39" row="5" col="4" usability="1" points="4">O</Field>
        <Field id="F40" row="5" col="5" usability="1" points="5">L</Field>
        <Field id="F41" row="5" col="6" usability="1" points="0">S</Field>
        <Field id="F42" row="6" col="0" usability="1" points="7">I</Field>
        <Field id="F43" row="6" col="1" usability="2" points="7">A</Field>
        <Field id="F44" row="6" col="2" usability="1" points="7">A</Field>
        <Field id="F45" row="6" col="3" usability="1" points="2">A</Field>
        <Field id="F46" row="6" col="4" usability="1" points="0">Z</Field>
        <Field id="F47" row="6" col="5" usability="1" points="8">I</Field>
        <Field id="F48" row="6" col="6" usability="1" points="0">O</Field>
    </Jungle>
    <SnakeTypes>
        <SnakeType id="A0" points="10" amount="1">
            <Word>ADA</Word>
            <NeighborhoodStructure type="Distance">
                <Parameter value="1" />
            </NeighborhoodStructure>
        </SnakeType>
        <SnakeType id="A1" points="10" amount="1">
            <Word>AMY</Word>
            <NeighborhoodStructure type="Distance">
                <Parameter value="1" />
            </NeighborhoodStructure>
        </SnakeType>
        <SnakeType id="A2" points="10" amount="1">
            <Word>ANN</Word>
            <NeighborhoodStructure type="Distance">
                <Parameter value="1" />
            </NeighborhoodStructure>
        </SnakeType>
        <SnakeType id="A3" points="10" amount="1">
            <Word>AVA</Word>
            <NeighborhoodStructure type="Distance">
                <Parameter value="1" />
            </NeighborhoodStructure>
        </SnakeType>
        <SnakeType id="A4" points="10" amount="1">
            <Word>BEA</Word>
            <NeighborhoodStructure type="Distance">
                <Parameter value="1" />
            </NeighborhoodStructure>
        </SnakeType>
        <SnakeType id="A5" points="10" amount="1">
            <Word>ELA</Word>
            <NeighborhoodStructure type="Distance">
                <Parameter value="1" />
            </NeighborhoodStructure>
        </SnakeType>
        <SnakeType id="A6" points="10" amount="1">
            <Word>EVA</Word>
            <NeighborhoodStructure type="Distance">
                <Parameter value="1" />
            </NeighborhoodStructure>
        </SnakeType>
        <SnakeType id="A7" points="10" amount="1">
            <Word>IDA</Word>
            <NeighborhoodStructure type="Distance">
                <Parameter value="1" />
            </NeighborhoodStructure>
        </SnakeType>
        <SnakeType id="A8" points="10" amount="1">
            <Word>INA</Word>
            <NeighborhoodStructure type="Distance">
                <Parameter value="1" />
            </NeighborhoodStructure>
        </SnakeType>
        <SnakeType id="A9" points="10" amount="1">
            <Word>ISA</Word>
            <NeighborhoodStructure type="Distance">
                <Parameter value="1" />
            </NeighborhoodStructure>
        </SnakeType>
        <SnakeType id="A10" points="10" amount="1">
            <Word>LEA</Word>
            <NeighborhoodStructure type="Distance">
                <Parameter value="1" />
            </NeighborhoodStructure>
        </SnakeType>
        <SnakeType id="A11" points="10" amount="1">
            <Word>LIA</Word>
            <NeighborhoodStructure type="Distance">
                <Parameter value="1" />
            </NeighborhoodStructure>
        </SnakeType>
        <SnakeType id="A12" points="10" amount="1">
            <Word>LIN</Word>
            <NeighborhoodStructure type="Distance">
                <Parameter value="1" />
            </NeighborhoodStructure>
        </SnakeType>
        <SnakeType id="A13" points="10" amount="1">
            <Word>LIV</Word>
            <NeighborhoodStructure type="Distance">
                <Parameter value="1" />
            </NeighborhoodStructure>
        </SnakeType>
        <SnakeType id="A14" points="10" amount="1">
            <Word>MIA</Word>
            <NeighborhoodStructure type="Distance">
                <Parameter value="1" />
            </NeighborhoodStructure>
        </SnakeType>
        <SnakeType id="A15" points="10" amount="1">
            <Word>PIA</Word>
            <NeighborhoodStructure type="Distance">
                <Parameter value="1" />
            </NeighborhoodStructure>
        </SnakeType>
        <SnakeType id="A16" points="10" amount="1">
            <Word>RIA</Word>
            <NeighborhoodStructure type="Distance">
                <Parameter value="1" />
            </NeighborhoodStructure>
        </SnakeType>
        <SnakeType id="A17" points="10" amount="1">
            <Word>SUE</Word>
            <NeighborhoodStructure type="Distance">
                <Parameter value="1" />
            </NeighborhoodStructure>
        </SnakeType>
        <SnakeType id="A18" points="10" amount="1">
            <Word>UTE</Word>
            <NeighborhoodStructure type="Distance">
                <Parameter value="1" />
            </NeighborhoodStructure>
        </SnakeType>
        <SnakeType id="A19" points="10" amount="1">
            <Word>ZOE</Word>
            <NeighborhoodStructure type="Distance">
                <Parameter value="1" />
            </NeighborhoodStructure>
        </SnakeType>
    </SnakeTypes>
    <Snakes />
</SnakeHunt>

=== nemouu/wordsnake-hunt/res/sh_p4_problem_instance.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE SnakeHunt SYSTEM "snakehunt.dtd">
<SnakeHunt>
    <Time unit="s">
        <Limit>10.0</Limit>
    </Time>
    <Jungle rows="5" cols="8" signs="ABCDEFGHIJKLMNOPQRSTUVWXYZ">
        <Field id="F0" row="0" col="0" usability="1" points="1">N</Field>
        <Field id="F1" row="0" col="1" usability="1" points="1">G</Field>
        <Field id="F2" row="0" col="2" usability="1" points="1">R</Field>
        <Field id="F3" row="0" col="3" usability="1" points="1">N</Field>
        <Field id="F4" row="0" col="4" usability="1" points="1">T</Field>
        <Field id="F5" row="0" col="5" usability="1" points="1">A</Field>
        <Field id="F6" row="0" col="6" usability="1" points="1">R</Field>
        <Field id="F7" row="0" col="7" usability="1" points="1">E</Field>
        <Field id="F8" row="1" col="0" usability="1" points="1">H</Field>
        <Field id="F9" row="1" col="1" usability="1" points="1">I</Field>
        <Field id="F10" row="1" col="2" usability="1" points="1">E</Field>
        <Field id="F11" row="1" col="3" usability="1" points="1">I</Field>
        <Field id="F12" row="1" col="4" usability="1" points="1">T</Field>
        <Field id="F13" row="1" col="5" usability="1" points="1">A</Field>
        <Field id="F14" row="1" col="6" usability="1" points="1">T</Field>
        <Field id="F15" row="1" col="7" usability="1" points="1">Ä</Field>
        <Field id="F16" row="2" col="0" usability="1" points="1">C</Field>
        <Field id="F17" row="2" col="1" usability="1" points="1">R</Field>
        <Field id="F18" row="2" col="2" usability="1" points="1">N</Field>
        <Field id="F19" row="2" col="3" usability="1" points="1">N</Field>
        <Field id="F20" row="2" col="4" usability="1" points="1">E</Field>
        <Field id="F21" row="2" col="5" usability="1" points="1">N</Field>
        <Field id="F22" row="2" col="6" usability="1" points="1">S</Field>
        <Field id="F23" row="2" col="7" usability="1" points="1">T</Field>
        <Field id="F24" row="3" col="0" usability="1" points="1">G</Field>
        <Field id="F25" row="3" col="1" usability="1" points="1">R</Field>
        <Field id="F26" row="3" col="2" usability="1" points="1">L</Field>
        <Field id="F27" row="3" col="3" usability="1" points="1">P</Field>
        <Field id="F28" row="3" col="4" usability="1" points="1">T</Field>
        <Field id="F29" row="3" col="5" usability="1" points="1">L</Field>
        <Field id="F30" row="3" col="6" usability="1" points="1">K</Field>
        <Field id="F31" row="3" col="7" usability="1" points="1">U</Field>
        <Field id="F32" row="4" col="0" usability="1" points="1">E</Field>
        <Field id="F33" row="4" col="1" usability="1" points="1">L</Field>
        <Field id="F34" row="4" col="2" usability="1" points="1">S</Field>
        <Field id="F35" row="4" col="3" usability="1" points="1">A</Field>
        <Field id="F36" row="4" col="4" usability="1" points="1">R</Field>
        <Field id="F37" row="4" col="5" usability="1" points="1">A</Field>
        <Field id="F38" row="4" col="6" usability="1" points="1">T</Field>
        <Field id="F39" row="4" col="7" usability="1" points="1">A</Field>
    </Jungle>
    <SnakeTypes>
        <SnakeType id="A0" points="1" amount="1">
            <Word>ÄSKULAPNATTER</Word>
            <NeighborhoodStructure type="Distance">
                <Parameter value="2" />
            </NeighborhoodStructure>
        </SnakeType>
        <SnakeType id="A1" points="1" amount="1">
            <Word>RINGELNATTER</Word>
            <NeighborhoodStructure type="Distance">
                <Parameter value="2" />
            </NeighborhoodStructure>
        </SnakeType>
        <SnakeType id="A2" points="1" amount="1">
            <Word>SCHLINGNATTER</Word>
            <NeighborhoodStructure type="Distance">
                <Parameter value="2" />
            </NeighborhoodStructure>
        </SnakeType>
    </SnakeTypes>
</SnakeHunt>

=== nemouu/wordsnake-hunt/res/sh_p2_incomplete.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE SnakeHunt SYSTEM "snakehunt.dtd" >
<SnakeHunt>
	<Time unit="s">
		<Limit>10.0</Limit>
	</Time>
	<Jungle rows="5" cols="10" signs="ABCDEFGHIJKLMNOPQRSTUVWXYZ">
	</Jungle>
	<SnakeTypes>
		<SnakeType id="A0" points="1" amount="1">
			<Word>DIE</Word>
			<NeighborhoodStructure type="Distance">
				<Parameter value="1" />
			</NeighborhoodStructure>
		</SnakeType>
		<SnakeType id="A1" points="1" amount="1">
			<Word>DIES</Word>
			<NeighborhoodStructure type="Distance">
				<Parameter value="1" />
			</NeighborhoodStructure>
		</SnakeType>
		<SnakeType id="A2" points="1" amount="1">
			<Word>DIESE</Word>
			<NeighborhoodStructure type="Distance">
				<Parameter value="1" />
			</NeighborhoodStructure>
		</SnakeType>
		<SnakeType id="A3" points="1" amount="1">
			<Word>DIESES</Word>
			<NeighborhoodStructure type="Distance">
				<Parameter value="1" />
			</NeighborhoodStructure>
		</SnakeType>
		<SnakeType id="A4" points="1" amount="1">
			<Word>DIESEN</Word>
			<NeighborhoodStructure type="Distance">
				<Parameter value="1" />
			</NeighborhoodStructure>
		</SnakeType>
		<SnakeType id="A5" points="1" amount="1">
			<Word>DIESER</Word>
			<NeighborhoodStructure type="Distance">
				<Parameter value="1" />
			</NeighborhoodStructure>
		</SnakeType>
	</SnakeTypes>
</SnakeHunt>

=== nemouu/wordsnake-hunt/res/test_for_writing_in_incomplete_file.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE SnakeHunt SYSTEM "snakehunt.dtd">
<SnakeHunt>
  <Time unit="s">
    <Limit>1.0</Limit>
    <Elapsed>2.0</Elapsed>
  </Time>
  <Jungle rows="2" cols="3" signs="asdertg" />
  <SnakeTypes>
    <SnakeType id="A0" points="1" amount="1">
      <Word>abcdefghij</Word>
      <NeighborhoodStructure type="Distance">
        <Parameter value="2" />
      </NeighborhoodStructure>
    </SnakeType>
    <SnakeType id="A1" points="21" amount="31">
      <Word>hjgzhi</Word>
      <NeighborhoodStructure type="Distance">
        <Parameter value="2" />
      </NeighborhoodStructure>
    </SnakeType>
  </SnakeTypes>
</SnakeHunt>

=== nemouu/wordsnake-hunt/res/sh_p14_incomplete.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE SnakeHunt SYSTEM "snakehunt.dtd" >
<SnakeHunt>
    <Time unit="ms">
        <Limit>100</Limit>
	</Time>
	<Jungle rows="10" cols="10" signs="EHLMNPRUV">
	</Jungle>
    <SnakeTypes>
        <SnakeType id="A0" points="115" amount="4">
            <Word>RUHR</Word>
            <NeighborhoodStructure type="Distance">
                <Parameter value="1" />
            </NeighborhoodStructure>
        </SnakeType>
        <SnakeType id="A1" points="131" amount="4">
            <Word>LENNE</Word>
            <NeighborhoodStructure type="Distance">
                <Parameter value="1" />
            </NeighborhoodStructure>
        </SnakeType>
        <SnakeType id="A2" points="213" amount="4">
            <Word>VOLME</Word>
            <NeighborhoodStructure type="Distance">
                <Parameter value="1" />
            </NeighborhoodStructure>
        </SnakeType>
        <SnakeType id="A3" points="63" amount="4">
            <Word>ENNEPE</Word>
            <NeighborhoodStructure type="Distance">
                <Parameter value="1" />
            </NeighborhoodStructure>
        </SnakeType>
    </SnakeTypes>
</SnakeHunt>
